### ISSUE TITLE
IOS 9 update 

### ISSUE THREAD

**Issue by Ezat** [bluekitchen/btstack#10]
Hello!
When you will update it to ios9 ?
Thank you so much for your efforts.

**Comment by Fadi5555** [comment]
Me too I updated my device to iOS 9
And waiting for update this useful tweak

**Comment by mringwal** [comment]
Hi. What problem do you have on iOS 9? I just installed and started BTstack GPS and it is working.

**Comment by Ezat** [comment]
I think BTstack not compatible with (controllers for all) tweak.
![image](https://cloud.githubusercontent.com/assets/12213390/10546851/48c7c46e-7439-11e5-8183-bf8b55b2338a.jpeg)

**Comment by mringwal** [comment]
I see. In this case, please contact the author of Controllers for All.

**Comment by Ezat** [comment]
Oh .. Thank you.
