### ISSUE TITLE
ESP32 compile error: bitalloc-sbc.o needed by libbtstack.a

### ISSUE THREAD

**Issue by pavestru** [bluekitchen/btstack#106]
This exact issue was reported in #87 and "resolved" (not really) by "randomly running `make clean` and then `make flash`". I was able to reproduce it by running `rm -rf build && make`. You can also reproduce it by building an esp-idf example with btstack for the first time.
```
CC build/btstack/3rd-party/bluedroid/decoder/srce/alloc.o
make[1]: *** No rule to make target `3rd-party/bluedroid/decoder/srce/bitalloc-sbc.o', needed by `libbtstack.a'.  Stop.
make: *** [component-btstack-build] Error 2
```
Running `make` second time right after that seems to always build the project correctly.

**Comment by mringwal** [comment]
hi. It looks like this is a bug in make, especially make 3.8.1 that's installed by the latest Xcode on macOS and on Ubuntu 14.04.1 LTS. Using make 4.2.1, it compiles correctly.
