### ISSUE TITLE
How to distinguish a pairing is justworks or numeric comparison

### ISSUE THREAD

**Issue by LuckyHowl** [bluekitchen/btstack#109]
Hi，
I porting btstack to BCM20702B， it work new. But there are some problems with SSP pairing.
I set the local IO capacity to SSP_IO_CAPABILITY_DISPLAY_YES_NO, and the peer device set to 
SSP_IO_CAPABILITY_NO_INPUT_NO_OUTPUT. I can't distinguish the is justworks or numeric comparison.
I expect to implement a function: when the pairing is justworks will auto accept, and when the pairing is 
numeric comparison will notify user to comfirm.
Could you tell how to do it? Thanks~

**Comment by mringwal** [comment]
hi. in both cases we get an User Confirmation Request Event from the Bluetooth Controller. As the numeric comparison is the result of some random data put into a crypto operation, you might assume that it's just works if the number is zero.

**Comment by LuckyHowl** [comment]
Hi mringwal:
Thank for your answer. 
As you said, assume that it's justworks if the number is zero. I can get an non-zero number when the IO capacity is NO_INPUT_NO_OUTPUT.
I have an idea, could I distinguish it by the local IO capacity and the remote IO capacity?

**Comment by mringwal** [comment]
Yes, the chosen pairing method is based on the IO Capabilities and MITM yes/no. However, I don't think you should need to do that.

Could you post a packet log (txt or .pklg) for the case where the number is no zero and you've selected NO_INPUT_NO_OUTPUT?

Found this in the Bluetooth spec: "... If the Host has output capability (DisplayYesNo or KeyboardOnly), it shall display the Numeric_Value until the Simple Pairing Complete event is received...'' - so if you have NO_INPUT_NO_OUTPUT, only Just Works is possible anyway, and you should not display anything. The spec even indicates that you should just accept it: "If the Host has no input and no output it shall reply with the User Confirmation Request Reply command."

**Comment by LuckyHowl** [comment]
Hi mringwal, thank for your answer.

Nowday I use the IO capability to distinguish the pairing is justworks or numeric comparison, my code as fellow:

                case HCI_EVENT_USER_CONFIRMATION_REQUEST:
                    // inform about user confirmation request
                    log_info("SSP User Confirmation Request with numeric value '%06"PRIu32"'\n", little_endian_read_32(packet, 8));
                    log_info("SSP User Confirmation Auto accept\n");
                    if(btstack_status.local_ssp_io_capability == 0x01 && 
                        btstack_status.peer_ssp_io_capability == 0x01)
                    {
                        log_info("User confirm\n");
                        memset(&message, 0, sizeof(message));
                        hci_event_user_confirmation_request_get_bd_addr(packet, message.sec_pairing.bd_addr);
                        memcpy(btstack_status.peer_bd_addr, message.sec_pairing.bd_addr, sizeof(message.sec_pairing.bd_addr));
                        message.sec_pairing.key = little_endian_read_32(packet, 8);
                        message.sec_pairing.mode = NUMERIC_COMPARISON_PAIRING_MODE;
                        Paxme_BtMessageEmit(GAP_PAIRING_EVT, &message);
                    }
                    else
                    {
                        log_info("Justworks\n");
                        hci_event_user_confirmation_request_get_bd_addr(packet, event_addr);
                        gap_ssp_confirmation_response(event_addr);
                    }

                    break;

I set my device IO capability to NO_INPUT_NO_OUTPUT, and use an Android phone connect to my device,  the packet log as fellow:


[02:13:02.510] EVT <=(04) 04 0A F6 8B FB 16 8D A0 0C 02 5A 01 
LOG -- event_handler.1882: Connection_incoming: A0:8D:16:FB:8B:F6, type 1
LOG -- create_connection_for_bd_addr_and_type.185: create_connection_for_addr A0:8D:16:FB:8B:F6, type ff
LOG -- hci_run.3146: sending hci_accept_connection_request, remote eSCO 0
[02:13:02.510] CMD =>(01) 09 04 07 F6 8B FB 16 8D A0 01 
[02:13:02.510] EVT <=(04) 6E 00 
[02:13:02.520] EVT <=(04) 0F 04 00 01 09 04 
[02:13:02.540] EVT <=(04) 03 0B 00 0E 00 F6 8B FB 16 8D A0 01 00 
LOG -- event_handler.1906: Connection_complete (status=0) A0:8D:16:FB:8B:F6
LOG -- event_handler.1919: New connection: handle 14, A0:8D:16:FB:8B:F6
LOG -- hci_emit_nr_connections_changed.3763: BTSTACK_EVENT_NR_CONNECTIONS_CHANGED 1
[02:13:02.540] EVT <=(04) 61 01 01 
[02:13:02.540] CMD =>(01) 1B 04 02 0E 00 
[02:13:02.540] EVT <=(04) 1B 03 0E 00 05 
[02:13:02.540] ACL <=(02) 0E 20 0A 00 06 00 01 00 0A 02 02 00 02 00 
[02:13:02.540] EVT <=(04) 6E 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.540] ACL =>(02) 0E 00 10 00 0C 00 01 00 0B 02 08 00 02 00 00 00 80 02 00 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:02.550] EVT <=(04) 0F 04 00 01 1B 04 
[02:13:02.550] EVT <=(04) 0B 0B 00 0E 00 BF FE CF FE DB FF 7B 87 
LOG -- event_handler.1985: HCI_EVENT_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE, bonding flags 6, eSCO 1
[02:13:02.550] EVT <=(04) 6E 00 
[02:13:02.560] EVT <=(04) 32 09 F6 8B FB 16 8D A0 01 00 03 
[02:13:02.560] EVT <=(04) 31 06 F6 8B FB 16 8D A0 
LOG -- event_handler.2033: Remote io capability:1

LOG -- event_handler.2034: Remote OOB data:0

LOG -- event_handler.2035: Remote authentication req:3

LOG -- hci_run.3198: IO Capability Request received, stack bondable 1, io cap 3
LOG -- gap_mitm_protection_required_for_security_level.3872: gap_mitm_protection_required_for_security_level 0
[02:13:02.560] CMD =>(01) 2B 04 09 F6 8B FB 16 8D A0 03 00 04 
[02:13:02.560] EVT <=(04) 6E 00 
[02:13:02.560] ACL <=(02) 0E 20 0A 00 06 00 01 00 0A 03 02 00 03 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.560] ACL =>(02) 0E 00 14 00 10 00 01 00 0B 03 0C 00 03 00 00 00 06 00 00 00 00 00 00 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:02.560] EVT <=(04) 0E 0A 01 2B 04 00 F6 8B FB 16 8D A0 
[02:13:02.560] EVT <=(04) 6E 00 
[02:13:02.570] EVT <=(04) 13 05 01 0E 00 02 00 
[02:13:02.800] EVT <=(04) 33 0A F6 8B FB 16 8D A0 3A DC 05 00 
LOG -- packet_handler.289: SSP User Confirmation Request with numeric value '384058'

LOG -- packet_handler.290: SSP User Confirmation Auto accept

LOG -- packet_handler.304: Justworks

[02:13:02.800] CMD =>(01) 2C 04 06 F6 8B FB 16 8D A0 
[02:13:02.800] EVT <=(04) 6E 00 
[02:13:02.810] EVT <=(04) 0E 0A 01 2C 04 00 F6 8B FB 16 8D A0 
[02:13:02.870] EVT <=(04) 36 07 00 F6 8B FB 16 8D A0 
[02:13:02.880] EVT <=(04) 18 17 F6 8B FB 16 8D A0 32 B6 67 68 B0 EA AB 0F 02 C1 10 D2 BB 7C C2 3D 04 
LOG -- gap_store_link_key_for_bd_addr.352: gap_store_link_key_for_bd_addr: A0:8D:16:FB:8B:F6, type 4
[02:13:02.890] ACL <=(02) 0E 20 0C 00 08 00 01 00 02 04 04 00 01 00 42 00 
LOG -- gap_request_security_level.3896: gap_request_security_level 0, current level 0
LOG -- hci_emit_security_level.3794: hci_emit_security_level 0 for handle e
[02:13:02.890] EVT <=(04) E0 03 0E 00 00 
LOG -- l2cap_hci_event_handler.2018: l2cap - security level update
LOG -- l2cap_hci_event_handler.2027: channel state 5: actual 0 >= required 0?
LOG -- l2cap_emit_incoming_connection.895: L2CAP_EVENT_INCOMING_CONNECTION addr A0:8D:16:FB:8B:F6 handle 0xe psm 0x1 local_cid 0x40 remote_cid 0x42
[02:13:02.890] EVT <=(04) 72 0E F6 8B FB 16 8D A0 0E 00 01 00 40 00 42 00 
LOG -- l2cap_accept_connection.2138: L2CAP_ACCEPT_CONNECTION local_cid 0x40
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.890] ACL =>(02) 0E 00 10 00 0C 00 01 00 03 04 08 00 40 00 42 00 00 00 00 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:02.890] EVT <=(04) 6E 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- [02:13:02.900] EVT <=(04) 6E 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 2 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 2 used of 8
[02:13:02.910] EVT <=(04) 13 05 01 0E 00 02 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
[02:13:02.920] ACL <=(02) 0E 20 10 00 0C 00 01 00 04 05 08 00 40 00 00 00 01 02 00 01 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 4, state 11
LOG -- l2cap_signaling_handle_configure_request.2190: Remote MTU 256
LOG -- l2cap_signaling_handle_configure_request.2192: Remote MTU 256 larger than outgoing buffer, only using MTU = 96
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.920] ACL =>(02) 0E 00 12 00 0E 00 01 00 05 05 0A 00 42 00 00 00 00 00 01 02 60 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:02.920] ACL <=(02) 0E 20 0E 00 0A 00 01 00 05 01 06 00 40 00 00 00 00 00 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 5, state 11
LOG -- l2cap_stop_rtx.995: l2cap_stop_rtx for local cid 0x40
LOG -- l2cap_signaling_handle_configure_response.2260: l2cap_signaling_handle_configure_response
LOG -- l2cap_emit_channel_opened.870: L2CAP_EVENT_CHANNEL_OPENED status 0x0 addr A0:8D:16:FB:8B:F6 handle 0xe psm 0x1 local_cid 0x40 remote_cid 0x42 local_mtu 96, remote_mtu 96, flush_timeout 0
[02:13:02.920] EVT <=(04) 70 16 00 F6 8B FB 16 8D A0 0E 00 01 00 40 00 42 00 60 00 60 00 00 00 01 
[02:13:02.920] EVT <=(04) 6E 00 
[02:13:02.960] ACL <=(02) 0E 20 18 00 14 00 40 00 06 00 00 00 0F 35 03 19 12 00 00 F0 35 05 0A 00 00 FF FF 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- l2cap_emit_can_send_now.842: L2CAP_EVENT_CHANNEL_CAN_SEND_NOW local_cid 0x40
[02:13:02.960] EVT <=(04) 78 02 40 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- l2cap_send_prepared.1059: l2cap_send_prepared cid 0x40, handle 14, 1 credit used
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.960] ACL =>(02) 0E 00 0F 00 0B 00 42 00 07 00 00 00 06 00 03 36 00 00 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:02.960] EVT <=(04) 6E 00 
[02:13:02.990] EVT <=(04) 13 05 01 0E 00 02 00 
[02:13:02.990] ACL <=(02) 0E 20 0C 00 08 00 01 00 06 06 04 00 40 00 42 00 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 6, state 12
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:02.990] ACL =>(02) 0E 00 0C 00 08 00 01 00 07 06 04 00 40 00 42 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
LOG -- l2cap_emit_channel_closed.889: L2CAP_EVENT_CHANNEL_CLOSED local_cid 0x40
[02:13:02.990] EVT <=(04) 71 02 40 00 
LOG -- l2cap_stop_rtx.995: l2cap_stop_rtx for local cid 0x40
[02:13:02.990] EVT <=(04) 6E 00 
[02:13:03.020] ACL <=(02) 0E 20 0C 00 08 00 01 00 02 07 04 00 01 00 43 00 
LOG -- gap_request_security_level.3896: gap_request_security_level 0, current level 0
LOG -- hci_emit_security_level.3794: hci_emit_security_level 0 for handle e
[02:13:03.020] EVT <=(04) E0 03 0E 00 00 
LOG -- l2cap_hci_event_handler.2018: l2cap - security level update
LOG -- l2cap_hci_event_handler.2027: channel state 5: actual 0 >= required 0?
LOG -- l2cap_emit_incoming_connection.895: L2CAP_EVENT_INCOMING_CONNECTION addr A0:8D:16:FB:8B:F6 handle 0xe psm 0x1 local_cid 0x41 remote_cid 0x43
[02:13:03.020] EVT <=(04) 72 0E F6 8B FB 16 8D A0 0E 00 01 00 41 00 43 00 
LOG -- l2cap_accept_connection.2138: L2CAP_ACCEPT_CONNECTION local_cid 0x41
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:03.020] ACL =>(02) 0E 00 10 00 0C 00 01 00 03 07 08 00 41 00 43 00 00 00 00 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:03.020] EVT <=(04) 6E 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 2 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 2 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 2 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- [02:13:03.030] EVT <=(04) 6E 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 3 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 3 used of 8
[02:13:03.060] EVT <=(04) 13 05 01 0E 00 02 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
[02:13:03.060] ACL <=(02) 0E 20 10 00 0C 00 01 00 04 08 08 00 41 00 00 00 01 02 00 01 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 4, state 11
LOG -- l2cap_signaling_handle_configure_request.2190: Remote MTU 256
LOG -- l2cap_signaling_handle_configure_request.2192: Remote MTU 256 larger than outgoing buffer, only using MTU = 96
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:03.060] ACL =>(02) 0E 00 12 00 0E 00 01 00 05 08 0A 00 43 00 00 00 00 00 01 02 60 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:03.060] ACL <=(02) 0E 20 0E 00 0A 00 01 00 05 02 06 00 41 00 00 00 00 00 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 5, state 11
LOG -- l2cap_stop_rtx.995: l2cap_stop_rtx for local cid 0x41
LOG -- l2cap_signaling_handle_configure_response.2260: l2cap_signaling_handle_configure_response
LOG -- l2cap_emit_channel_opened.870: L2CAP_EVENT_CHANNEL_OPENED status 0x0 addr A0:8D:16:FB:8B:F6 handle 0xe psm 0x1 local_cid 0x41 remote_cid 0x43 local_mtu 96, remote_mtu 96, flush_timeout 0
[02:13:03.060] EVT <=(04) 70 16 00 F6 8B FB 16 8D A0 0E 00 01 00 41 00 43 00 60 00 60 00 00 00 01 
[02:13:03.070] EVT <=(04) 6E 00 
[02:13:03.090] EVT <=(04) 13 05 01 0E 00 02 00 
[02:13:03.100] ACL <=(02) 0E 20 18 00 14 00 41 00 06 00 00 00 0F 35 03 19 01 00 00 F0 35 05 0A 00 00 FF FF 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- l2cap_emit_can_send_now.842: L2CAP_EVENT_CHANNEL_CAN_SEND_NOW local_cid 0x41
[02:13:03.100] EVT <=(04) 78 02 41 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- l2cap_send_prepared.1059: l2cap_send_prepared cid 0x41, handle 14, 1 credit used
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:03.100] ACL =>(02) 0E 00 64 00 60 00 43 00 07 00 00 00 5B 00 54 36 00 60 36 00 5D 09 00 00 0A 00 01 00 01 09 00 01 36 00 03 19 11 01 09 00 04 36 00 0E 36 00 03 19 01 00 36 00 05 19 00 03 08 01 09 00 05 36 00 03 19 10 02 09 00 06 36 00 09 09 65 6E 09 00 6A 09 01 00 09 00 09 36 00 09 36 00 06 19 11 01 09 11 02 09 01 04 00 00 00 4E 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:03.100] EVT <=(04) 6E 00 
[02:13:03.130] ACL <=(02) 0E 20 1C 00 18 00 41 00 06 00 01 00 13 35 03 19 01 00 00 F0 35 05 0A 00 00 FF FF 04 00 00 00 4E 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- l2cap_emit_can_send_now.842: L2CAP_EVENT_CHANNEL_CAN_SEND_NOW local_cid 0x41
[02:13:03.130] EVT <=(04) 78 02 41 00 
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- l2cap_send_prepared.1059: l2cap_send_prepared cid 0x41, handle 14, 1 credit used
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 1 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:03.130] ACL =>(02) 0E 00 1B 00 17 00 43 00 07 00 01 00 12 00 0F 00 25 0C 53 50 50 20 53 74 72 65 61 6D 65 72 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
[02:13:03.130] EVT <=(04) 6E 00 
[02:13:03.160] EVT <=(04) 13 05 01 0E 00 02 00 
[02:13:03.160] ACL <=(02) 0E 20 0C 00 08 00 01 00 06 09 04 00 41 00 43 00 
LOG -- l2cap_signaling_handler_channel.2328: L2CAP signaling handler code 6, state 12
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_number_free_acl_slots_for_connection_type.386: ACL classic buffers: 0 used of 8
LOG -- hci_send_acl_packet_fragments.559: hci_send_acl_packet_fragments entered
LOG -- hci_send_acl_packet_fragments.565: hci_send_acl_packet_fragments loop entered
LOG -- hci_send_acl_packet_fragments.590: hci_send_acl_packet_fragments loop before send (more fragments 0)
[02:13:03.160] ACL =>(02) 0E 00 0C 00 08 00 01 00 07 09 04 00 41 00 43 00 
LOG -- hci_send_acl_packet_fragments.608: hci_send_acl_packet_fragments loop after send (more fragments 0)
LOG -- hci_send_acl_packet_fragments.617: hci_send_acl_packet_fragments loop over
LOG -- l2cap_emit_channel_closed.889: L2CAP_EVENT_CHANNEL_CLOSED local_cid 0x41
[02:13:03.160] EVT <=(04) 71 02 41 00 
LOG -- l2cap_stop_rtx.995: l2cap_stop_rtx for local cid 0x41
[02:13:03.160] EVT <=(04) 6E 00 
[02:13:03.310] EVT <=(04) 13 05 01 0E 00 01 00 
[02:13:07.070] EVT <=(04) 05 04 00 0E 00 13 
LOG -- hci_emit_discoverable_enabled.3812: BTSTACK_EVENT_DISCOVERABLE_ENABLED 1
[02:13:07.070] EVT <=(04) 66 01 01 
do_disconnect_evt-369
LOG -- hci_shutdown_connection.827: Connection closed: handle 0xe, A0:8D:16:FB:8B:F6
LOG -- hci_emit_nr_connections_changed.3763: BTSTACK_EVENT_NR_CONNECTIONS_CHANGED 0
[02:13:07.070] EVT <=(04) 61 01 00
