### ISSUE TITLE
Is there any event to indicate LE pairing finish?

### ISSUE THREAD

**Issue by LuckyHowl** [bluekitchen/btstack#111]
I try to use SM_EVENT_AUTHORIZATION_RESULT event to indicate the LE pairing finish and tell the user the pairing is successful or not. But this event never emit yet.

**Comment by mringwal** [comment]
SM_EVENT_AUTHORIZATION_RESULT is supposed to be for authorized access, which is authentication + asking the user once more. 

Anyway, you'd like to get an event for sm pairing complete and that one actually is missing - I've stumbled upon that just last week. We'll add a sm_event_pairing_complete or so event in the next days.

**Comment by LuckyHowl** [comment]
Thank you very much!

**Comment by mringwal** [comment]
btw. on the develop branch, you'll get a SM_EVENT_PAIRING_COMPLETE, see sm_pairing_peripheral/central.
