### ISSUE TITLE
Hi,How can I get the name and device class of the remote device when I am connected to the device?

### ISSUE THREAD

**Issue by 907038134** [bluekitchen/btstack#112]
How can I get the name and device class of the remote device when I am connected to the device?

**Comment by 907038134** [comment]
thanks!

**Comment by 907038134** [comment]
I haven't found the process of pair failure, can you give me directions? thanks!

**Comment by mringwal** [comment]
For Bluetooth Classic, you can gap_remote_name_request when connected or not. You may also get the remote name as part of the Extended Inquiry Response (see gap_inquiry example). The Class of Device is only available as part of the inquiry.

For LE, you might get the name as part of the advertisements and/or scan response. After connected, you can use the gatt_client to find the GAP Name Characteristic.

**Comment by mringwal** [comment]
This is not a chat. Please try to explain better what you've tried, what you've expected, and what happened. Also, general "how to" might be better on the BTstack  mailing list. http://groups.google.com/group/btstack-dev

**Comment by 907038134** [comment]
thanks!
