### ISSUE TITLE
rfcomm_init in hsp_init causes issues

### ISSUE THREAD

**Issue by ajraymond** [bluekitchen/btstack#113]
Hi,

I think the following rfcomm_init() shouldn't be part of hsp_hs_init(), as it can conflict with other blocks making use of rfcomm (if they are initialized before the call to hsp_hs_init()).
https://github.com/bluekitchen/btstack/blob/5457d1b1be44dd5c4189844dd1feb8db26162401/src/classic/hsp_hs.c#L288

Anyhow, your demos (and my own code) explicitly call rfcomm_init() before calling hfp/hsp/spp_init(), so this shouldn't be an issue:
https://github.com/bluekitchen/btstack/blob/fe052a7b1b3efbd364c17a75fdb0b4fc89e76e2e/example/hsp_hs_demo.c#L295

**Comment by mringwal** [comment]
Hi Alexandre. Thanks for reporting this bug. You're right and the rfcomm_init() should not be there. Fixed on develop (and will propagate to master eventually)
