### ISSUE TITLE
hfp_ag not sending 'OK' response for AT+CLCC

### ISSUE THREAD

**Issue by skoperst** [bluekitchen/btstack#127]
https://github.com/bluekitchen/btstack/blob/62abb699839330d8f329e6c9ff2d317460d5555a/src/classic/hfp_ag.c#L1636-L1647

I tested against a headunit which would ignore next command because no 'OK' was sent after AT+CLCC request.
According to spec it should always return 'OK'.
See HFP_V1.7.0.pdf page 80

**Comment by skoperst** [comment]
Didn't pay attention to this: 
`hfp_connection->ok_pending = 1;`

**Comment by mringwal** [comment]
hi. hfp_ag hasn't been tested much and I just improved the 'can send now' management on the develop brach. Does it work there?

**Comment by skoperst** [comment]
Yes, I pulled the develop changes for the HF/AG. Now works nicely.
Thanks.

**Comment by mringwal** [comment]
that's a happy coincident. please reach out again if you stumble into other issues.
