### ISSUE TITLE
Getting BTStack Working on iOS

### ISSUE THREAD

**Issue by MattSich** [bluekitchen/btstack#13]
So I've been trying to connect to a BT 4.0 Classic device over SPP. I've tried a few different approaches and I feel like BTstack is my best option but I'm running into some problems. 
I noticed this: 
<img width="1004" alt="screen shot 2016-05-06 at 1 16 49 pm" src="https://cloud.githubusercontent.com/assets/6378097/15080609/0d7a2cf0-138d-11e6-8160-cbc7e48ff258.png">
What is the reason for using the /usr/lib/libBTstack.dylib path instead of a local path? 
I tried using install_name_tool to rewrite the path but was unable to. 
I tried to build run your makefile for the iOS port but got this issue:
<img width="470" alt="screen shot 2016-05-06 at 1 29 15 pm" src="https://cloud.githubusercontent.com/assets/6378097/15080998/a125a834-138e-11e6-9dfa-443fdf5eea41.png">

Is there any way to run BTstack with a non-jailbroken device? I'm not looking to upload to the store but I'd like to be able to add the app to non-jailbroken devices

Any help would be greatly appreciated!

**Comment by mringwal** [comment]
Unfortunately, there's no way to use BTstack without a Jailbreak. First, we need to disable system bluetooth and then directly talk to the Bluetooth module, which is not possible without a JB.

libBTstack.dylib is in /usr/lib/ so all apps/daemons can easily link to it. The install name isn't a problem on JB.
