### ISSUE TITLE
ESP32 a2dp_source_demo compiling Error

### ISSUE THREAD

**Issue by b4b4k** [bluekitchen/btstack#130]
Hi,
there is small issue to compile a2dp_source_demo example:

![image](https://user-images.githubusercontent.com/30823073/40414444-6f5ddc62-5e8d-11e8-8b1c-58ee3259d864.png)

**Comment by mringwal** [comment]
Hi. Could you run ./integrate_btstack.py and try again? It builds on the build server

**Comment by b4b4k** [comment]
Thank you very much, Solved
