### ISSUE TITLE
script compile_gatt.py issue

### ISSUE THREAD

**Issue by Lefix2** [bluekitchen/btstack#132]
Hi,

Today I created a GATT service wich is composed of 3 characteristics.
To identify each characteristics, i used [characteristic user descriptor](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.descriptor.gatt.characteristic_user_description.xml).
Descriptors are static, so i used compile_gatt.py script and att_server_init() function.
But when setting utf8 string instead of value in the .gatt file, the ATT advertisement didn't work anymore.
In my case, [this line](https://github.com/bluekitchen/btstack/blob/master/tool/compile_gatt.py#L524) for the characteristic user descriptor parsing of the script
 is invalid and i had to change "size = size + len(value) - 2" to "size = size + len(value) " to get it work.
I think it's an error because [this line](https://github.com/bluekitchen/btstack/blob/master/tool/compile_gatt.py#L449) for the characteristic parsing seems ok!

Have a good day.

**Comment by mringwal** [comment]
Thanks! Fixed on develop branch.
