### ISSUE TITLE
Compiling on mac fails with libusb_set_debug deprecated

### ISSUE THREAD

**Issue by arashbi** [bluekitchen/btstack#134]
I am trying examples on ports/libusb forlder on my mac.
The compilation fails with 

> ➜  libusb git:(master) make
> cc -I. -I../../src/ble -I../../src/classic -I../../src -I../../3rd-party/hxcmod-player -I../../3rd-party/micro-ecc -I../../3rd-party/bluedroid/decoder/include -I../../3rd-party/bluedroid/encoder/include -g -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Werror -Wunused-parameter -Wredundant-decls -Wsign-compare -I../../platform/posix -I../../platform/embedded -I../../3rd-party/tinydir -I/usr/local/Cellar/libusb/1.0.22/include/libusb-1.0   -c -o hci_transport_h2_libusb.o ../../platform/libusb/hci_transport_h2_libusb.c
> ../../platform/libusb/hci_transport_h2_libusb.c:852:5: error: 'libusb_set_debug' is deprecated [-Werror,-Wdeprecated-declarations]
>     libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_ERROR);
>     ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:1299:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
> LIBUSB_DEPRECATED_FOR(libusb_set_option)
> ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:89:49: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
> #define LIBUSB_DEPRECATED_FOR(f) __attribute__((deprecated))
>                                                 ^
> ../../platform/libusb/hci_transport_h2_libusb.c:895:5: error: 'libusb_set_debug' is deprecated [-Werror,-Wdeprecated-declarations]
>     libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_WARNING);
>     ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:1299:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
> LIBUSB_DEPRECATED_FOR(libusb_set_option)
> ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:89:49: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
> #define LIBUSB_DEPRECATED_FOR(f) __attribute__((deprecated))
>                                                 ^
> ../../platform/libusb/hci_transport_h2_libusb.c:930:5: error: 'libusb_set_debug' is deprecated [-Werror,-Wdeprecated-declarations]
>     libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_WARNING);
>     ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:1299:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
> LIBUSB_DEPRECATED_FOR(libusb_set_option)
> ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:89:49: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
> #define LIBUSB_DEPRECATED_FOR(f) __attribute__((deprecated))
>                                                 ^
> ../../platform/libusb/hci_transport_h2_libusb.c:1141:13: error: 'libusb_set_debug' is deprecated [-Werror,-Wdeprecated-declarations]
>             libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_ERROR);
>             ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:1299:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
> LIBUSB_DEPRECATED_FOR(libusb_set_option)
> ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:89:49: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
> #define LIBUSB_DEPRECATED_FOR(f) __attribute__((deprecated))
>                                                 ^
> ../../platform/libusb/hci_transport_h2_libusb.c:1171:13: error: 'libusb_set_debug' is deprecated [-Werror,-Wdeprecated-declarations]
>             libusb_set_debug(NULL, LIBUSB_LOG_LEVEL_WARNING);
>             ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:1299:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
> LIBUSB_DEPRECATED_FOR(libusb_set_option)
> ^
> /usr/local/Cellar/libusb/1.0.22/include/libusb-1.0/libusb.h:89:49: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
> #define LIBUSB_DEPRECATED_FOR(f) __attribute__((deprecated))
> 

libusb version is 1.0.22.

**Comment by mringwal** [comment]
Thanks for reporting. I'll have a look at soon. Until then, you could comments all calls to libusb_set_debug.

**Comment by mringwal** [comment]
Fixed in https://github.com/bluekitchen/btstack/commit/648316077732288aefab85c6d4d379dc8e8dc149
