### ISSUE TITLE
esp32 ported then a2dp sink demo audio broken

### ISSUE THREAD

**Issue by jhpark555** [bluekitchen/btstack#136]
Hello,

At esp32 board, I modified something like below,

1. In  handle_pcm_data functions,
static void handle_pcm_data(int16_t * data, int num_samples, int num_channels, int sample_rate, void * context)
{
    UNUSED(sample_rate);
    UNUSED(context);    

_/* Add this to put out the audio via i2s  */
	size_t bytes_written;
	i2s_write(0, data, num_samples*num_channels*2, &bytes_written, portMAX_DELAY);_

}

2. At app_main()
int app_main(void){

    printf("BTstack: setup\n");

    // enable packet logger
    // hci_dump_open(NULL, HCI_DUMP_STDOUT);

 _// add this initialize for I2S
    i2s_config_t i2s_config = {
         .mode = I2S_MODE_MASTER | I2S_MODE_TX,                                  // Only TX
         
        .sample_rate = 44100,
        .bits_per_sample = 16,                                              
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,                           //2-channels
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
        .dma_buf_count = 6,
        .dma_buf_len = 60,                                                      //
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1                                //Interrupt level 1
    };

    i2s_driver_install(0, &i2s_config, 0, NULL);
    i2s_pin_config_t pin_config = {
	.bck_io_num = 26, //CONFIG_I2S_BCK_PIN,
	.ws_io_num = 25, //CONFIG_I2S_LRCK_PIN,
	.data_out_num = 22, //CONFIG_I2S_DATA_PIN,
    .data_in_num = -1                                                       //Not used
    };

    i2s_set_pin(0, &pin_config);_

 3. At media_processing_init()
enable sbc decoder call 
static int media_processing_init(avdtp_media_codec_configuration_sbc_t configuration){
    if (media_initialized) return 0;

    _btstack_sbc_decoder_init(&state, mode, handle_pcm_data, NULL);_

These all 3 modifications were enabled to audio out through I2S.
It look s work well but about 30sec or more the audio sound abruptly stopped. I checked with PC and smartphomes.  What was wrong?  
I only enabled bluetooth classic option in menuconfiguration.

Thanks.

**Comment by mringwal** [comment]
I didn't try to implement i2s output on the esp32 yet. Disabling the packet log is certainly necessary. My guess would be that sending the data synchronously (blocking) using i2s_write also blocks/delays the Bluetooth communication. The writing to I2S should happen either independently. You may write the audio data to a ring buffer and use a second thread to actually write it. Maybe this could be interesting too: http://bluekitchen-gmbh.com/a2dp-sink-and-source-on-stm32-f4-discovery-board/
