### ISSUE TITLE
Dead Link to PDF Documentation

### ISSUE THREAD

**Issue by rei-vilo** [bluekitchen/btstack#141]
On the main page, the link for the PDF documentation...

> Documentation: HTML, [PDF](http://bluekitchen-gmbh.com/btstack_master.pdf)

... results in a `Page not Found.` error.

<img width="400" alt="capture 2018-06-20 a 18 22 01" src="https://user-images.githubusercontent.com/951776/41671289-f50fb864-74b6-11e8-806b-43febaa2c46f.png">

**Comment by mringwal** [comment]
Hey Rei,tThanks for reporting! It should have gone to this  [PDF](http://bluekitchen-gmbh.com/btstack.pdf) but is fixed now. See you next week..
