### ISSUE TITLE
none-include of classic API

### ISSUE THREAD

**Issue by Lefix2** [bluekitchen/btstack#150]
When ENABLE_CLASSIC is not defined, all header files are included.
Is it a choice?

https://github.com/bluekitchen/btstack/blob/7284beeecf4402e2dab3aabb82ca53a9de2b1e31/src/btstack.h#L86-L118

**Comment by mringwal** [comment]
Kind of. They should not be included. When setting in it up, I didn't want to break anything. Yet, btstack.h is only used by the examples, so it wouldn't hurt to fix it finally.

**Comment by mringwal** [comment]
Fixed on develop branch
