### ISSUE TITLE
iOS 11 compatibility !

### ISSUE THREAD

**Issue by aestheticsglowexe** [bluekitchen/btstack#152]
i use btstack on my ipad 3 on ios 9 and it’s working fine. but now electra jailbreak released and i can’t use it on ios 11 idk what’s the problem actually but controllersforall is working fine. btstack is the problem it needs to be upgraded to work on ios 11 generally. please guys if anyone could offer help and make it work on ios 11 or if anyone could reach the developer and talk to him to upgrade it or if u r a developer we can discuss it on Reddit. that’s it xx.

**Comment by mringwal** [comment]
see https://github.com/bluekitchen/btstack/issues/27

BTstack works on iOS 11 as far as I know, but Controllers For All doesn't.
If there are actual issues in BTstack, I'm happy to hear about them.
