### ISSUE TITLE
A little confused.....

### ISSUE THREAD

**Issue by XxDanxX182** [bluekitchen/btstack#157]
Hey there!

So I’m a little bit confused on whether or not BTstack is now fully updated/works for iOS 11 and now we just have to wait for controllersforall to be updated. I’m just wondering what is needed at this point in order for us to be able to connect a controller to iPhone. 

Looking forward to your reply, Thanks!

**Comment by mringwal** [comment]
Sorry, don't know. There have been pull requests, please give them a try.
https://github.com/bluekitchen/btstack/pull/218
