### ISSUE TITLE
hid_host_demo stops receiving data packets

### ISSUE THREAD

**Issue by ASPrabhu96** [bluekitchen/btstack#158]
I was trying to pair a playstation 4 dualshock controller with an esp32 running the hid_host_demo in the btstack examples. It pairs with the device, and starts reading packets. however, after 26 packets it randomly stops (the connection is still maintained, the devices are paired). I am not sure as to why this is happening. Any idea ? or, if anyone has tried something similar and are willing to share source code it would be great! thanks!

**Comment by mringwal** [comment]
do you get HID Control messages? The demo prints "HID Control:..". An HID Host is supposed to answer these requests. Could you try with e.g. a Bluetooth keyboard as well?

**Comment by mringwal** [comment]
No response, closing.
