### ISSUE TITLE
Mbedtls compile error

### ISSUE THREAD

**Issue by darkyline** [bluekitchen/btstack#164]
Hello Matthias,

I switched on develop branch but I still get `'mbedtls_ec_group' undeclared (first use in this function)` error

Thanks.

**Comment by mringwal** [comment]
If you have HAVE_MBEDTLS_ECC_P256 defined in btstack_config.h, mbedtls_ec_group will be (should be...) declared in line 141: https://github.com/bluekitchen/btstack/blob/develop/src/btstack_crypto.c#L141

**Comment by darkyline** [comment]
It works thanks !

**Comment by mringwal** [comment]
Thanks for reporting the compile error :)
