### ISSUE TITLE
Rfcomm.c “ try to detect authentication errors: drop link key if multiplexer closed before first channel got opened”

### ISSUE THREAD

**Issue by 907038134** [bluekitchen/btstack#167]
hi，Excuse me，I have a question about rfcomm. C：
        What do you mean “try to detect authentication errors: drop link key if multiplexer closed before first channel got opened”？As shown below.
        I am very confused: sometimes when the program runs here, the device connection is disconnected by the android phone.
       And you can tell me, what's going to lead to this process?
       What is the purpose of this process? Why does this happen when link key exists? I'm really confused.
       Can you help with the analysis?
       Thank you very much!

        case RFCOMM_MULTIPLEXER_SEND_UA_0_AND_DISC:
            // try to detect authentication errors: drop link key if multiplexer closed before first channel got opened
            if (!multiplexer->at_least_one_connection){
                log_info("TODO: no connections established - delete link key prophylactically");
                // hci_send_cmd(&hci_delete_stored_link_key, multiplexer->remote_addr);
            }
            log_info("Sending UA #0");
            log_info("Closing down multiplexer");
            multiplexer->state = RFCOMM_MULTIPLEXER_CLOSED;
            rfcomm_send_ua(multiplexer, 0);

            rfcomm_multiplexer_finalize(multiplexer);
            l2cap_disconnect(l2cap_cid, 0x13);
            break;

**Comment by mringwal** [comment]
First, the code is commented out, so there's just a log.

The idea was this: if we bond with a device and the device deletes its link key then we'll try to start encryption using our link key, but the other one doesn't have the key. In this case, the authentication fails. 

To get a working connection, the only way is to delete our key as well, and then pair again the next time. This should not be initiated by rfcomm, and in any case, I don't think the RFCOMM Multiplexer can be opened (the l2cap connection) without authentication, so it's the wrong place as well. I'll just delete that code.

Why are you looking so close at the code? Feel free to discuss/ask on the BTstack developer mainling list, too.
