### ISSUE TITLE
CVSD PLC introducing garbage noise into stream

### ISSUE THREAD

**Issue by skoperst** [bluekitchen/btstack#178]
https://github.com/bluekitchen/btstack/blob/6a765b5d8d4395f33c09903477fff876e8f85a33/src/classic/btstack_cvsd_plc.c#L260

memset works on bytes not on int16_t, therefore whenever you get 2 missing frames or more (happens not only because of bad link, can also happen because of phone BT behavior when line in silence) you get unpredictable noise which can ruin your mood.

Need to change into:
`memset(out, 0, CVSD_FS * sizeof(SAMPLE_FORMAT));`

**Comment by skoperst** [comment]
Also a few lines above that memcpy, also needs `sizeof`

**Comment by milamikica** [comment]
thanks for helping
