### ISSUE TITLE
Using l2cap channel after free

### ISSUE THREAD

**Issue by skoperst** [bluekitchen/btstack#181]
There is an issue casing my board to seg-fault.
In l2cap.c, calling: 
`l2cap_finialize_channel_close(channel);  // -- remove from list`

Then if **ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE** is enabled, it will try to access freed memory:
`channel->con_handle`

I think best to nullify the freed channel and then check for NULL.

https://github.com/bluekitchen/btstack/blob/2f98d3c60ab84a4e7ec4a33c528cd323900cd4a3/src/l2cap.c#L1493-L1509

**Comment by mringwal** [comment]
Thanks for reporting! Indeed, setting channel to NULL and checking at the beginning of the ERTM  code was the best option.
