### ISSUE TITLE
windows-winusb make with error

### ISSUE THREAD

**Issue by wslkh** [bluekitchen/btstack#185]
Hi, I tried to build the port 'windows-winusb' but failed:

> avrcp_browsing_controller.o: In function `avrcp_browsing_connect':
C:\msys64\home\lkh\btstack\port\windows-winusb/../../src/classic/avrcp_browsing_controller.c:167: undefined reference to `l2cap_create_ertm_channel'
avrcp_browsing_controller.o: In function `avrcp_browsing_controller_configure_incoming_connection':
C:\msys64\home\lkh\btstack\port\windows-winusb/../../src/classic/avrcp_browsing_controller.c:776: undefined reference to `l2cap_accept_ertm_connection'

I see the same function is used by other files without error. Any clue? Thanks.

**Comment by mringwal** [comment]
AVRCP requires L2CAP Enhanced Retransmission Mode and it's not enabled in the windows-winusb port.

Please add #define ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE to btstack_config.h and make clean && make

**Comment by wslkh** [comment]
It works, thanks, mringwal.
