### ISSUE TITLE
How to terminate an active ATT server connection?

### ISSUE THREAD

**Issue by amitv87** [bluekitchen/btstack#190]
In the [le_counter](https://github.com/bluekitchen/btstack/blob/master/example/le_counter.c#L160) example, is there a way to trigger a termination request similar to notification request.

In other words is there an api to end an active connection?
I browsed through the docs and couldn't find one.

**Comment by mringwal** [comment]
You can disconnect an active HCI Connection with gap_disconnect(hci_con_handle). See src/gap.h. You get the con handle with every att read/write callback

**Comment by amitv87** [comment]
Great that works, thanks.
