### ISSUE TITLE
Hosting an ATT service without broadcasting advertisement data

### ISSUE THREAD

**Issue by amitv87** [bluekitchen/btstack#192]
Is it possible to host an ATT service without advertising it?
I wish to make the service reachable to devices which are aware about the host mac address

**Comment by mringwal** [comment]
Yes, you can have an GATT Server without enabling advertising. In that case, nobody can connect to it though and you'd need to create an outgoing (central/mastere) connection first.

Advertisements are necessary to accept incoming connections.

please post general questions on BTstack Dev Mailing.
