### ISSUE TITLE
Baud rate problem

### ISSUE THREAD

**Issue by chunhua523** [bluekitchen/btstack#2]
Hi,

I'm using MSP430F5438A + CC2564B to send ADC data to an android phone.
It's successful but has a slow data rate, less than one data per sec.
I've referred to spp_and_le_counter.c, and set timers to send notifications.
Even though I set the timeout at 1ms, it's useless.

My target data rate is 1.5k per sec. How could I resolve this problem?

This is my demo vedio: https://youtu.be/vOHGzDM1oJg

Thanks!

**Comment by wenjiegong** [comment]
you can not set baud rate on RFCOMM which will transfer the data as fast as it can. The article 'How Fast is Bluetooth?' is useful to understand the issue. You may change the MTU on L2CAP packets. If a system has a smaller L2CAP MTU, the size of RFCOMM data will also be restricted.

**Comment by mringwal** [comment]
I've posted here: https://groups.google.com/d/msg/btstack-dev/BuBDK915-fI/gLT49Vyi2EYJ
