### ISSUE TITLE
ATT indication BUG. callback NULL pointer  btstack/src/ble/att_server.c  line 140

### ISSUE THREAD

**Issue by jcstarna** [bluekitchen/btstack#200]
static void att_handle_value_indication_notify_client(uint8_t status, uint16_t client_handle, uint16_t attribute_handle){
    btstack_packet_handler_t packet_handler = att_server_packet_handler_for_handle(attribute_handle);
    if (!packet_handler) return;
    uint8_t event[7];
    int pos = 0;
    event[pos++] = ATT_EVENT_HANDLE_VALUE_INDICATION_COMPLETE;
    event[pos++] = sizeof(event) - 2;
    event[pos++] = status;
    little_endian_store_16(event, pos, client_handle);
    pos += 2;
    little_endian_store_16(event, pos, attribute_handle);
    (*att_client_packet_handler)(HCI_EVENT_PACKET, 0, &event[0], sizeof(event));
} 

I've changed line 140:
`(*att_client_packet_handler)(HCI_EVENT_PACKET, 0, &event[0], sizeof(event));`
for:
`(*packet_handler)(HCI_EVENT_PACKET, 0, &event[0], sizeof(event));`

A null pointer reference occurs when `att_client_packet_handler` it is not set when i guess packet_handler should be used.

**Comment by mringwal** [comment]
Thanks for reporting. You're fix is correct, I've applied it as a444112b on the develop branch.
