### ISSUE TITLE
Q: Arduino -> BTstackManager::loop

### ISSUE THREAD

**Issue by gvdhoven** [bluekitchen/btstack#206]
If i want to port my Raspberry Pi peripheral to Android (INO); i have 2 questions:
1) Is the peripheral already working?
https://github.com/bluekitchen/btstack/blob/7284beeecf4402e2dab3aabb82ca53a9de2b1e31/port/arduino/examples/LEPeripheral/LEPeripheral.ino#L1
2) If i want to combine this with mDNS and a Websocket server, i see the following code in loop;

```
void loop(void){
    BTstack.loop();
}
```

Which in turn calls this:
```
void BTstackManager::loop(void){
    // process data from/to Bluetooth module
    hal_uart_dma_process();
    // BTstack Run Loop
    btstack_run_loop_embedded_execute_once();
}
```

Wouldn't it then be enough to do something like this:
```
void loop(void){
    // process data from/to Bluetooth module
    hal_uart_dma_process();

    // process other events (like websocket etc)
    while (1) {
    }
}
```

**Comment by mringwal** [comment]
Sorry for missing this so long.

1. Nope. For Arduino, where there's no way to run a python script to compile the gatt db, we've created att_db_util, which allows to setup an ATT DB similar to other Arduino APIs, so the ground work is there.

2. The BTstackManager::loop needs to constantly polled, e.g. to receive every byte from the UART and or send new packets. In your proposed loop, the while (1) is never left, hence, neither hal_uart_dma_process or btstack_run_loop_embedded_execute_once are called ever again.

In general, and especially on an Raspi, I'd suggest to use the native API directly. For sockets, there's a socket_connection.c in the platform/daemon code that allows to use sockets without threads from the BTstack run loop.
