### ISSUE TITLE
WinUSB: HFP not working on Windows versions before Windows 8.1

### ISSUE THREAD

**Issue by mailtoxiong** [bluekitchen/btstack#212]
Hi @mringwal ,

How could TEST HFP  with [ Bluetooth Music BOX--has mic and speaker]  ?

 [ Bluetooth Music BOX--has mic and speaker]: SONY ,SRS-BTV 5

--taken few days with the open source code , pray for someone's helps .
  
  When i used the HPF  :

  the function in  [sco_demo_util.c]: 

------------------------------------------------------
     audio_initialize(CVSD_SAMPLE_RATE);
------------------------------------------------------

// return 1 if ok
static int audio_initialize(int sample_rate){

    // -- output -- //

    // init buffers
    memset(audio_output_ring_buffer_storage, 0, sizeof(audio_output_ring_buffer_storage));
    btstack_ring_buffer_init(&audio_output_ring_buffer, audio_output_ring_buffer_storage, sizeof(audio_output_ring_buffer_storage));

    // config and setup audio playback
    const btstack_audio_sink_t * audio_sink = btstack_audio_sink_get_instance();
    if (!audio_sink) return 0;
------------------------------------------------------
always  [  audio_initialize(CVSD_SAMPLE_RATE); ]  failed 
How could  do or initialized for some function ,before use this .  
Thank you in advance!

Regards,

Kerwin XIONG

![image](https://user-images.githubusercontent.com/33509267/56575236-d2d4ce00-65f7-11e9-89fc-ce5a86a7d006.png)

![image](https://user-images.githubusercontent.com/33509267/56627552-e3795880-6678-11e9-8a5e-94eba47e040e.png)

**Comment by mringwal** [comment]
Looks like you're running BTstack on Windows. What Windows version do you use? SCO over HCI, which is needed for HFP, requires Windows 8.1 or higher. See warning in your last screenshot.

**Comment by mailtoxiong** [comment]
@mringwal , thanks for your reply .
I knew the reminder in log,and i am using win 7 sp1 version system . If have no more choice  for using HFP in win 7 ,such as add dll  or sth else ?  Thanks a lot !

**Comment by mringwal** [comment]
Well, BTstack is very flexible. I've used WinUSB on Windows and it support Isochronous USB Endpoints from Windows 8.1. I guess it would be possible to write a Windows kernel driver and use that instead with older versions. I don't know much about Windows, though.

**Comment by mailtoxiong** [comment]
Hello @mringwal .Thank you so much for patiently answers. 
After used btstach in Windows 8 (previous is win 7 sp1,at last changed to Win 8.1 sytem ).
Now ,i am already moved the source code to embeded sytem (like STM32,as below shown)
![image](https://user-images.githubusercontent.com/33509267/56798185-e034c700-6848-11e9-9dc0-277e8e51c10b.png)
My question is :
  a. When i tried  to send SINE SCO data  :
      #define SCO_DEMO_MODE      SCO_DEMO_MODE_SINE
      
      In sco_demo_util.c ,
      void sco_demo_send(hci_con_handle_t sco_handle)
{
....

       // test silence

# if 0
       //  original open source code
       memset(sco_packet+3, 0, sco_payload_length);
# else
       // modified code  ,  2019.04.29
       //scotest_Array   ,sine data
        memset(sco_packet+3, 0x6A, sco_payload_length);
     //  memcpy(sco_packet+3, scotest_Array, sco_payload_length);
# endif

....
}

     Means ,i added some code for send all data like 0x6a..
      Always  shown the error logs like:
       
![image](https://user-images.githubusercontent.com/33509267/56798453-55080100-6849-11e9-9e88-759ecbb24465.png)
    
        
       Could you help me or give me some advice.Anyway ,thank you so much .

**Comment by mringwal** [comment]
What Bluetooth Controller (chip) do you use? Is it connected via UART or USB? (also closing as there's no issue on Windows 8.1). Please post on the developer mailing list with regular questions.

**Comment by mailtoxiong** [comment]
What Bluetooth Controller (chip) do you use? 
-----RTK8761 ,Realtek 
Is it connected via UART or USB? (also closing as there's no issue on Windows 8.1). 
-----yes ,via this for  firmware download (seems no issue on Windows 8.1,But not works on Embeded PCB  system )
Please post on the developer mailing list with regular questions.
-----How could i mail the developer list ?

**Comment by mringwal** [comment]
I have no experience with the RTK8761 - didn't see much documentation about it.

It seems to be an USB device. If it works with Windows 8.1 but not with embedded, your embedded driver probably is not working correctly.

Mailing list: http://groups.google.com/group/btstack-dev

**Comment by mailtoxiong** [comment]
Actually , maybe you know google link and google search  in locked by China ,so,can not link in this Mailing list website .
Mailing list: http://groups.google.com/group/btstack-dev

If HAS any other website for instead and i could do mailing .

Thanx a lot for ever took more interrupts for you .

**Comment by mringwal** [comment]
Sorry. The mailing list is hosted by Google. It looks like it's necessary to create a "Google Account" for your email address to join - which is not possible for you then.
