### ISSUE TITLE
ESP-IDF component micro-cc moved

### ISSUE THREAD

**Issue by pedrominatel** [bluekitchen/btstack#213]
The component micro-ecc was moved from ESP-IDF folder ESP_IDF/components/ to ESP_IDF/components/bootloader/subproject/components

ESP-IDF version: 4.0dev (master branch)

To solve this I've created a symbolic as workaround solution.

**Comment by pedrominatel** [comment]
Error message:

`make: *** No rule to make target 'component-micro-ecc-build', needed by 'component-btstack-build'.  Stop.`

**Comment by mringwal** [comment]
hi Pedro. yupp, that's correct. I've updated the Makefile on the BTstack develop branch to use the micro-ecc from BTstack. Now, develop doesn't compile with ESP-IDF 3.2...

I guess the python integrate script could check what's needed if a general solution would be to complicated to support 3.2 and 4.x+

**Comment by mringwal** [comment]
hi. I've found a way to have BTstack only use it's internal copy, see 5ec47f0f9 (on develop branch)

**Comment by pedrominatel** [comment]
Thanks @mringwal for supporting this issue!

**Comment by Matheusmbgm** [comment]
Hi, someone have a update on this issue? I had a project with esp idf v3.2 using btstack and i had to update my esp idf to V4.0 (i guess thats the version number, its the newest version) so i could use OTA Security. After i did the update i have the same problem related in this topic. I tried to update btstack lib but i still have this problem.
