### ISSUE TITLE
How  to filter  BT device via company ID ,in the Inquiry process ?

### ISSUE THREAD

**Issue by mailtoxiong** [bluekitchen/btstack#217]
@mringwal 
  Hello , My Friend :
                   Thanks for your previous supports !
                   Could i ask for you about ： 
                     a. could i  filter BT sink device  v ia company ID ,in the Inquiry process ?
       
Yours Sincerely !
Kerwin

**Comment by mringwal** [comment]
During Inquiry, you can get:
- class of device
- bluetooth address (bdaddr) - which indicates the vendor of the Bluetooth Controller
- Extended Inquiry Response (EIR)- can contain what you like

Usually, people filter on device name. I'd recommend to set custom values in the EIR and check for that.
