### ISSUE TITLE
sco_demo_receive and sco_demo_send  data path？

### ISSUE THREAD

**Issue by sunxuezu2018** [bluekitchen/btstack#222]
hi bluekitchen，
      I want to know using sco_demo_send  to send data  using uart or not?  The demo does not send audio data by pcm interface, is it right?
thanks

**Comment by mringwal** [comment]
hi. the demos are cross-platform and only support SCO over HCI. SCO over HCI only works reliable with TI CC256x controllers. You can disable wide-band speech and directly connect PCM/I2S pins to an audio codec.
