### ISSUE TITLE
ESP32 Compilation Issue

### ISSUE THREAD

**Issue by JSnowden33** [bluekitchen/btstack#223]
I'm using the latest btstack on Windows 10 along with the latest esp-idf toolchain and msys2 release, but none of the example btstack projects will compile. I've followed the setup instructions in the README found in port/esp32. Any examples I try to compile will stop with this error which I can't find anywhere online:  

"*** No rule to make target 'component-micro-ecc-build', needed by 'component-btstack-build'. Stop."  

I noticed the micro-ecc folder found in "3rd-party" isn't present in the esp-idf directory after running "integrate_btstack.py", so I copied it over to esp-idf/components/btstack/3rd-party manually, but this didn't change compilation at all.

**Comment by mringwal** [comment]
hi. please switch to the develop branch of btstack and try again.
