### ISSUE TITLE
esp32 gatt notifications

### ISSUE THREAD

**Issue by Flint174** [bluekitchen/btstack#232]
Hello,
I am trying to create an hid host ble device. Let's say we have got ble client with characteristics listed below:

GATT browser - CHARACTERISTIC for SERVICE 00001812-0000-1000-8000-00805F9B34FB, [0x000f-0x0027]
[00:00:01.351] LOG -- gatt_client.c.127: GATT client timeout start, handle 0x00
    * characteristic: [0x0010-0x0011-0x0011], properties 0x06, uuid 2a4e
    * characteristic: [0x0012-0x0013-0x0015], properties 0x12, uuid 2a4d
    * characteristic: [0x0016-0x0017-0x0019], properties 0x12, uuid 2a4d
    * characteristic: [0x001e-0x001f-0x0021], properties 0x12, uuid 2a4d
    * characteristic: [0x001a-0x001b-0x001d], properties 0x12, uuid 2a4d
    * characteristic: [0x0022-0x0023-0x0023], properties 0x02, uuid 2a4b
    * characteristic: [0x0024-0x0025-0x0025], properties 0x02, uuid 2a4a
    * characteristic: [0x0026-0x0027-0x0027], properties 0x04, uuid 2a4c
[00:00:01.531] LOG -- gatt_client.c.135: GATT client timeout stop, handle 0x00

Could you tell the proper way to submit for notifications? The way I do this is:

for( itr = 0; itr < count; itr++ ) {
	dump_characteristic(&config_characteristic[itr]);
	gatt_client_listen_for_characteristic_value_updates( &hid_notification[itr], handle_gatt_client_event, connection_handle, &config_characteristic[itr] ); 

	if( gatt_client_write_client_characteristic_configuration(handle_gatt_client_event, connection_handle, &config_characteristic[itr], GATT_CLIENT_CHARACTERISTICS_CONFIGURATION_NOTIFICATION) != 0 ) {
		printf("\nNotification not supported. Query value of characteristic.\n");
	}
}

If I understood it right, "gatt_client_write_client_characteristic_configuration" creates a timer that emits no event after expiring

**Comment by mringwal** [comment]
hi. please ask user questions on the btstack developer google group. 

to enable notifications, you call gatt_client_write_client_characteristic_configuration, that's correct. However, you cannot call it in a loop. After the first call you need to wait for the Query Complete event (as in the examples) before calling the GATT Client again. There can only be one transaction at the same time and BTstack does not use (waste) memory to queue such requests.
