### ISSUE TITLE
avdtp_util.c "store_bit16" function return type error

### ISSUE THREAD

**Issue by moyaoyi** [bluekitchen/btstack#233]
avdtp_util.c: uint8_t store_bit16 function need return a value which type is uint16_t.
old code:
**uint8_t** store_bit16(**uint16_t bitmap**, int position, uint8_t value){
    if (value){
        bitmap |= 1 << position;
    } else {
        bitmap &= ~ (1 << position);
    }
    **return bitmap;**
}

after modified:
**uint16_t** store_bit16(uint16_t bitmap, int position, uint8_t value){
    if (value){
        bitmap |= 1 << position;
    } else {
        bitmap &= ~ (1 << position);
    }
    return bitmap;
}

**Comment by milamikica** [comment]
Thanks!

**Comment by moyaoyi** [comment]
It is my pleasure.
