### ISSUE TITLE
Avdtp_until.c: "avdtp_unpack_service_capabilities" function has some issue.

### ISSUE THREAD

**Issue by moyaoyi** [bluekitchen/btstack#234]
When I created an active A2DP connection, I need call avdtp_sink_get_all_capabilities function. But did not return correct all capabilities. Therefore I modified avdtp_unpack_serice_capabilities function and solved this issue. By the way, call avdtp_sink_get_capabilities function can get correct capabilities. May be there are some issue in my modified code, please help to modify.

**Before Modified:**
uint16_t avdtp_unpack_service_capabilities(avdtp_connection_t * connection, avdtp_capabilities_t * caps, uint8_t * packet, uint16_t size){
    if (size == 0) return 0;
    
    uint16_t registered_service_categories = 0;
    int pos = 0;
    int i;
    avdtp_service_category_t category = (avdtp_service_category_t)packet[pos++];
    uint8_t cap_len = packet[pos++];
   
    if (avdtp_unpack_service_capabilities_has_errors(connection, category, cap_len)) return 0;
    int processed_cap_len = 0;
    int rfa = 0;
    
    **while (pos < size)**{
        if (cap_len > size - pos){
            connection->reject_service_category = category;
            connection->error_code = BAD_LENGTH;
            return 0;
        }
        rfa = 0;
        processed_cap_len = pos;
        switch(category){
            case AVDTP_RECOVERY:                
                caps->recovery.recovery_type = packet[pos++];
                caps->recovery.maximum_recovery_window_size = packet[pos++];
                caps->recovery.maximum_number_media_packets = packet[pos++];
                break;
            case AVDTP_CONTENT_PROTECTION:
                caps->content_protection.cp_type = big_endian_read_16(packet, pos);
                pos+=2;
                
                caps->content_protection.cp_type_value_len = cap_len - 2;
                pos += caps->content_protection.cp_type_value_len;
                
                // connection->reject_service_category = category;
                // connection->error_code = UNSUPPORTED_CONFIGURATION;
                // support for content protection goes here
                break;
                
            case AVDTP_HEADER_COMPRESSION:
                caps->header_compression.back_ch  = packet[pos] >> 7; 
                caps->header_compression.media    = packet[pos] >> 6;
                caps->header_compression.recovery = packet[pos] >> 5;
                pos++;
                break;
            case AVDTP_MULTIPLEXING:                
                caps->multiplexing_mode.fragmentation = packet[pos++] >> 7;
                // read [tsid, tcid] for media, reporting. recovery respectively
                caps->multiplexing_mode.transport_identifiers_num = 3;
                for (i=0; i<caps->multiplexing_mode.transport_identifiers_num; i++){
                    caps->multiplexing_mode.transport_session_identifiers[i] = packet[pos++] >> 7;
                    caps->multiplexing_mode.tcid[i] = packet[pos++] >> 7;
                }
                break;
            case AVDTP_MEDIA_CODEC:   
                caps->media_codec.media_type = (avdtp_media_type_t)(packet[pos++] >> 4);
                caps->media_codec.media_codec_type = (avdtp_media_codec_type_t)(packet[pos++]);
                caps->media_codec.media_codec_information_len = cap_len - 2;
                caps->media_codec.media_codec_information = &packet[pos];
                pos += caps->media_codec.media_codec_information_len;
                break;
            case AVDTP_MEDIA_TRANSPORT:   
            case AVDTP_REPORTING:                
            case AVDTP_DELAY_REPORTING:                
                pos += cap_len;
                break;
            default:
                pos += cap_len;
                rfa = 1;
                break;
        }
        processed_cap_len = pos - processed_cap_len;
        
        if (cap_len == processed_cap_len){
            if (!rfa) {
                registered_service_categories = store_bit16(registered_service_categories, category, 1);
            }
            **if (pos < size-2)**{
                //int old_pos = pos;
                category = (avdtp_service_category_t)packet[pos++];
                cap_len = packet[pos++];
                if (avdtp_unpack_service_capabilities_has_errors(connection, category, cap_len)) return 0;
            }
        } 
    }
    return registered_service_categories;
}

**After Modified:**
uint16_t avdtp_unpack_service_capabilities(avdtp_connection_t * connection, avdtp_capabilities_t * caps, uint8_t * packet, uint16_t size){
    if (size == 0) return 0;
    
    uint16_t registered_service_categories = 0;
    int pos = 0;
    int i;
    avdtp_service_category_t category = (avdtp_service_category_t)packet[pos++];
    uint8_t cap_len = packet[pos++];
   
    if (avdtp_unpack_service_capabilities_has_errors(connection, category, cap_len)) return 0;
    int processed_cap_len = 0;
    int rfa = 0;
    
    **while (pos <= size)**{
        if (cap_len > size - pos){
            connection->reject_service_category = category;
            connection->error_code = BAD_LENGTH;
            return 0;
        }
        rfa = 0;
        processed_cap_len = pos;
        switch(category){
            case AVDTP_RECOVERY:                
                caps->recovery.recovery_type = packet[pos++];
                caps->recovery.maximum_recovery_window_size = packet[pos++];
                caps->recovery.maximum_number_media_packets = packet[pos++];
                break;
            case AVDTP_CONTENT_PROTECTION:
                caps->content_protection.cp_type = big_endian_read_16(packet, pos);
                pos+=2;
                
                caps->content_protection.cp_type_value_len = cap_len - 2;
                pos += caps->content_protection.cp_type_value_len;
                
                // connection->reject_service_category = category;
                // connection->error_code = UNSUPPORTED_CONFIGURATION;
                // support for content protection goes here
                break;
                
            case AVDTP_HEADER_COMPRESSION:
                caps->header_compression.back_ch  = packet[pos] >> 7; 
                caps->header_compression.media    = packet[pos] >> 6;
                caps->header_compression.recovery = packet[pos] >> 5;
                pos++;
                break;
            case AVDTP_MULTIPLEXING:                
                caps->multiplexing_mode.fragmentation = packet[pos++] >> 7;
                // read [tsid, tcid] for media, reporting. recovery respectively
                caps->multiplexing_mode.transport_identifiers_num = 3;
                for (i=0; i<caps->multiplexing_mode.transport_identifiers_num; i++){
                    caps->multiplexing_mode.transport_session_identifiers[i] = packet[pos++] >> 7;
                    caps->multiplexing_mode.tcid[i] = packet[pos++] >> 7;
                }
                break;
            case AVDTP_MEDIA_CODEC:   
                caps->media_codec.media_type = (avdtp_media_type_t)(packet[pos++] >> 4);
                caps->media_codec.media_codec_type = (avdtp_media_codec_type_t)(packet[pos++]);
                caps->media_codec.media_codec_information_len = cap_len - 2;
                caps->media_codec.media_codec_information = &packet[pos];
                pos += caps->media_codec.media_codec_information_len;
                break;
            case AVDTP_MEDIA_TRANSPORT:   
            case AVDTP_REPORTING:                
            case AVDTP_DELAY_REPORTING:                
                pos += cap_len;
                break;
            default:
                pos += cap_len;
                rfa = 1;
                break;
        }
        processed_cap_len = pos - processed_cap_len;
        
        if (cap_len == processed_cap_len){
            if (!rfa) {
                registered_service_categories = store_bit16(registered_service_categories, category, 1);
            }
            **if (pos <= size-2)**{
                //int old_pos = pos;
                category = (avdtp_service_category_t)packet[pos++];
                cap_len = packet[pos++];
                if (avdtp_unpack_service_capabilities_has_errors(connection, category, cap_len)) return 0;
            } **else {
                break;`
            }**
        } 
    }
    return registered_service_categories;
}

**Comment by milamikica** [comment]
Thank you for reporting it. We rewrote the code to be simpler (and correct).
