### ISSUE TITLE
How (and where in the code) to upload firmware into ATWILC3000?

### ISSUE THREAD

**Issue by flaforge1793** [bluekitchen/btstack#235]
Dear Bluekitchen,

I am not sure how to implement the atwilc3000 firmware upload using the btstack. I have placed the btstack_chipset_atwilc3000_download_firmware() function in the BTSTACK_Initialize() function like this:
`const hci_transport_t * transport = hci_transport_h4_instance(btstack_uart_block_embedded_instance());
    hci_init(transport, &config);
    hci_set_chipset(btstack_chipset_atwilc3000_instance());

    /* need to upload atwilc3000 firmware here? */
    btstack_chipset_atwilc3000_download_firmware(btstack_uart_block_embedded_instance(),115200,0,&atwilc3000_fw_data[0],271373,done);
    while(!isFirmwareUploadDone);
   
    // inform about BTstack state
    hci_event_callback_registration.callback = &packet_handler;`

Is this correct?
Thanks,
Francois.

**Comment by mringwal** [comment]
Hi. Please have a look at the samv71-xplained port:
https://github.com/bluekitchen/btstack/blob/master/port/samv71-xplained-atwilc3000/main.c

you need to split the main() code in two parts and do the main startup after the firmware was downloaded.
