### ISSUE TITLE
ESP32: btstack component

### ISSUE THREAD

**Issue by COM8** [bluekitchen/btstack#247]
I'm using `ESP-IDF v4.1-dev` and want to use `btstack` as a component.

What is the name of the `btstack` component?

When I try `btstack`:
```
idf_component_register(SRCS ${SOURCES}
                       INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR} $ENV{IDF_PATH}/components
                       REQUIRES btstack)
```
I'm getting `Failed to resolve component 'btstack'` once I run `idf.py build`.

**Comment by mringwal** [comment]
hi. port/esp32 currently lacks fully working CMakeList.txt files, see https://github.com/bluekitchen/btstack/issues/196

Please try to build using Make for now.

**Comment by COM8** [comment]
OK. Thank for the information!
