### ISSUE TITLE
pb_type_t prevents usage of btstack with nanopb

### ISSUE THREAD

**Issue by piotrkundu** [bluekitchen/btstack#249]
https://github.com/bluekitchen/btstack/blob/master/src/mesh/provisioning_device.c#L149

https://github.com/bluekitchen/btstack/blob/master/src/mesh/provisioning.h#L90

I'm adding nanopb to my project and got some name clashes. Perhaps renaming to *bt_pb_type_t* or something is enough. Unless there are other ways to avoid name clashes.

Running on develop branch at commit ec818a285

**Comment by mringwal** [comment]
Hi. We're already prefixing most common data types (e.g. btstack_linked_list, btstack_ring_buffer..). pb_type_t is only used inside mesh, we will rename it and let you know (probably mesh_pb_type_t)

**Comment by piotrkundu** [comment]
Great, thanks.
