### ISSUE TITLE
Combined SSP and GATT battery service

### ISSUE THREAD

**Issue by romainmoura** [bluekitchen/btstack#254]
Hello,
I try to mix an SPP profile with a battery service profile. This idea is to have the battery level displayed on the remote operating system. But I'm not sure if it is possible. I configured everything but it seems that the operating can connect the BR/EDR (ie SSP) but don't see at the same time the BLE profile (in the mean time I can see the BLE profile (and the battery level) with a tool bluethooth LE Explorer).
Do you know if it is possible ? 

Best regards,

**Comment by mringwal** [comment]
Please ask general questions on the BTstack mailing list: http://groups.google.com/group/btstack-dev

BTstack can provide SPP on Classic and a Battery Service on LE, but you probably would need to create both connections yourself. For most purposes, a dual-mode device will be used like two individual devices.
