### ISSUE TITLE
reading parameters for esco connection from master (LMP_eSCO_link_req)

### ISSUE THREAD

**Issue by danielsafrigin** [bluekitchen/btstack#271]
from the Bluetooth core:

> Master Initiates an eSCO Link 
> When establishing an eSCO link the master sends an LMP_eSCO_link_req PDU specifying all parameters. The slave may accept this with an LMP_accepted_ext PDU, reject it with an LMP_not_accepted_ext PDU, or respond with its own LMP_eSCO_link_req specifying alternatives for some or all parameters.

from my understanding, when the master tries to open an eSCO channel, he sends a request to the slave with his preferred parameters, then we replay with something like:

```
hci_send_cmd(&hci_accept_synchronous_connection, addr, 8000, 8000, max_latency, sco_voice_setting, retransmission_effort, packet_types);
```
afterward, master either accepts, keeps on negotiating or declines.

what I can not find is the first request with the master preferred parameters.

in btstack_event.h we have

`hci_event_synchronous_connection_complete_get_tx_packet_length`
but its after connection is complete, I was hoping for the same but for connection request.

**Comment by mringwal** [comment]
This is not an issue, please post on the BTstack Mailing List: http://groups.google.com/group/btstack-dev

SCO connections are initiated by hfp.c in hfp_setup_synchronous_connection()
