### ISSUE TITLE
Attribute ID List range adjustment

### ISSUE THREAD

**Issue by nathanRamaNoodles** [bluekitchen/btstack#274]
Certain fake Bluetooth devices want a specific range for the attribute ID list

At this [line in sdp_client.c](https://github.com/bluekitchen/btstack/blob/master/src/classic/sdp_client.c#L91):
change from this
```
static uint8_t des_attributeIDList[] = { 0x35, 0x05, 0x0A, 0x00, 0x01, 0xff, 0xff};  // Attribute: 0x0001 - 0x0100
```
to this
```
static uint8_t des_attributeIDList[] = { 0x35, 0x05, 0x0A, 0x00, 0x00, 0xff, 0xff};  // Attribute: 0x0001 - 0x0100  // Edit by Nathan Ramanathan: range is actually 0x0000 - 0xFFFF
```
Some of my Bluetooth devices were stubborn to connect without me changing the range.  I got these values from Bluez's stack with Wireshark.

**Comment by mringwal** [comment]
While we don't like to make changes to correct code, just because other implementations are bad (and wouldn't pass the official Bluetooth tests), we've adapted the range to query for the Service Handle, although it's no used on the develop branch. Well, maybe a user needs it for something.
