### ISSUE TITLE
support RTL8761B

### ISSUE THREAD

**Issue by zhaojh329** [bluekitchen/btstack#281]
support RTL8761B

**Comment by mringwal** [comment]
Hi. Looks like this is a USB Bluetooth Dongle. 

A quick search indicates a firmware has to be loaded before it can be used.
https://www.spinics.net/lists/linux-bluetooth/msg84456.html

Do you have  datasheets for it?, which also explains the firmware download? 
Any special need for this particular Bluetooth Controller?

I suggest to buy a normal CSR8510, or BCM20702 USB dongle.

**Comment by zhaojh329** [comment]
RTL8761B support Bluetooth 5.0.

**Comment by mringwal** [comment]
Which Bluetooth 5.0 features in detail? Every Bluetooth 4.0 Controller can be listed as 5.0 - with  identical features.
- LE Date Length Extension?
- 2 Mb-Phy?
- Long range?
