### ISSUE TITLE
Bug in hal_flash_bank_memory

### ISSUE THREAD

**Issue by Filip83** [bluekitchen/btstack#283]
In file btstack/platform/embedded/hal_flash_bank_memory.c function hal_flash_bank_memory_write write to memory is ignored if data value is 0xff. It would not be a problem but the offset variable is not incremented. Ther is a problem for example, if a Bluetooth address contains 0xff so it is not stored properly.

**Comment by mringwal** [comment]
Thanks for reporting. You're totally right about offset not getting incremented. I've fixed it on develop: https://github.com/bluekitchen/btstack/commit/3f054530e46651e83a64b59f82c62d32ddb4ebfb

Cheers!
