### ISSUE TITLE
classic bluetooth hid device auto reconnect

### ISSUE THREAD

**Issue by limithsieh** [bluekitchen/btstack#287]
I have work on example "hid_mouse_demo" for a while. 
I am wondering how to implement auto connection when the device had been pair with the host.
It seems hid_mouse have to send connection request to the host which had been pair with first.
Any suggestion for me? Thanks.

**Comment by mringwal** [comment]
Hi. Please have a look at the "hid_keyboard_demo" which implements re-connect.
You can call hid_device_connect(..) to trigger an outgoing connection.
