### ISSUE TITLE
Message Access Profile例子 Iphone无法正常工作

### ISSUE THREAD

**Issue by yywOwen** [bluekitchen/btstack#292]
查看Message Access Profile Specification 57页，如下图
![image](https://user-images.githubusercontent.com/66934547/84619825-d6689a00-af08-11ea-9604-4dc3b80ff27b.png)

Messages-Listing Format Version 1.1 MCE必要要支持.
测试的代码/map_client/map_client_test.c 313行supported_features = 0x1F; 需要修改为0x21F.蓝牙设备才可以与IPhone通讯

**Comment by mringwal** [comment]
Hi. Sorry we mainly speak english (and german, and serbian..). MAP isn't implemented yet, but I see you've found our work-in-progress code on the 'map' branch. Our development on MAP is currently stalled, what you do need it for? Feel free to send Pull Requests for the MAP branch.

**Comment by yywOwen** [comment]
China is at the forefront of the Bluetooth market, and hopefully it will support Chinese in the future, with more and more Chinese engineers involved

**Comment by mringwal** [comment]
HI. We don't exclude any language on purpose. We just stopped working on MAP due to other priorities.

Could you explain the issue in english please? You've highlighted Message Listing Format v1.1. Is it related to support for the Chinese market?

**Comment by vvhh2002** [comment]
This young guy just wants to implement MAP. Please forgive his rudeness. I think this issue could be closed.

**Comment by mringwal** [comment]
@vvhh2002 Thanks. No problem from my side. I still don't understand what @yywOwen wanted to report/request in this issue.

**Comment by mringwal** [comment]
Closing this as I don't understand the problem being reported.
