### ISSUE TITLE
"gap.c" missing ?

### ISSUE THREAD

**Issue by valesQQ** [bluekitchen/btstack#298]
Hi ! I'm trying to make btstack work on a nucleo F303RE with freeRTOS.
I was wondering why there was some headers files without a .c file corresponding, like for "gap.h". 
Is it just to get an idea of the function which need to be implemented by myself ? Or did I miss something ?

Thanks in advance !

**Comment by mringwal** [comment]
hi there. all functions defined in gap.h are either in hci.c or sm.c. There's a chance that these might eventually moved into a gap.c file, but so far they stay with their 'friends'.

See the other STM32 ports for example Makefiles and esp32 on how to use integrate with FreeRTOS
