### ISSUE TITLE
Link Key Conversion

### ISSUE THREAD

**Issue by caleedubya** [bluekitchen/btstack#302]
Within the BTStack manual - [https://bluekitchen-gmbh.com/btstack.pdf] is the following note:

5.7.7. Cross-transport Key Derivation for LE Secure Connections. In a dual- mode configuration, BTstack automatically generates an BR/EDR Link Key from the LE LTK via the Link Key Conversion function h6. It is then stored in the link key db.

My question is - how do we call the Link Key Conversion function h6? Any help, or even a example project would be much appreciated!

**Comment by mringwal** [comment]
No bug reported yet, discussion on mailing list.

**Comment by drewandre** [comment]
@mringwal is this a public mailing list or internal? I'd be interesting in hearing more about espressif development is it's public.

**Comment by mringwal** [comment]
On the public mailing list / BTstack Google Group: https://groups.google.com/forum/#!topic/btstack-dev/SRz8jYJXcLw

This was with regard to using BTstack in general, which is possible on the ESP32. For questions/support on the ESP-IDF version of Bluedroid, which is used by default on the ESP32, please use the Espressif forum or post issues on the esp-idf project.
