### ISSUE TITLE
HCI Security Level Assessment Incorrect

### ISSUE THREAD

**Issue by aroldxd** [bluekitchen/btstack#304]
The implementation of hci.c defines the minimum key length to be 16 [here](https://github.com/bluekitchen/btstack/blob/master/src/hci.c#L2917).

This leads to the `gap_security_level_for_connection` function assessing the security level of key lengths under 16 as level 0 as seen [here](https://github.com/bluekitchen/btstack/blob/master/src/hci.c#L4511).

The security level of an unauthenticated key of length 7 bytes is LEVEL_2 according to the bluetooth specification. BTstack assigns LEVEL_0. This leads to the l2cap channel establishment for any service (except sdp) failing when the communication partner supports security mode 4 (ssp)

**To Reproduce**
Establish a channel with any device supporting SSP and maximum key length of 7 bytes (or less than 16). 
(I used the a2dp_source_demo)

**Expected behavior**
BTstack should be able to connect to devices only supporting 7 byte keys.

**HCI Packet Logs**
Zipped log is attached.
[hci_dump_2.pklg.zip](https://github.com/bluekitchen/btstack/files/4911981/hci_dump_2.pklg.zip)
In the log file, line 231: key size is 7
line 232: security level 0 is emitted

**Environment:  (please complete the following information):**
 - Current BTstack branch: master
 - Bluetooth Controller CSR USB dongle
 - Remote device: xqBEAT 2.0 portable bluetooth speaker

I am aware that this can be mitigated by anyone using BTstack by calling: `gap_set_required_encryption_key_size(7);`

**Comment by mringwal** [comment]
Hi @aroldxd You're observation is correct - we've picked a minimum encryption key size of 16 to 'foster' secure connection. It looks like more devices than expected only support 7 byte of encryption key size - although I cannot even find an HCI Command to configure that from the host - e.g. the Wii Remote, and your Bluetooth speaker.

Long story short: we've set 7 as default on the develop branch. 

Final note: Security Level 4 - which requires Classic Secure Connections, which e.g. isn't supported on current macOS, so I don't think it is used anywhere - requires 16 bytes here.
