### ISSUE TITLE
AVRCP Commands failed in a2dp_sink_demo

### ISSUE THREAD

**Issue by jsplyy** [bluekitchen/btstack#314]
**Describe the bug**
AVRCP Commands failed in a2dp_sink_demo

**To Reproduce**
1. Run example 'a2dp_sink_demo '
2. Connect from remote device 'my android cell phone MI8'
3. Start action 'play music with one app on cell phone'
4. Input command 'L' or 'K' to pause or stop audio stream, will report Could not perform command

**Expected behavior**
expect that command could pause or stop audio stream

**HCI Packet Logs**
[hci_dump.pklg.zip](https://github.com/bluekitchen/btstack/files/5118174/hci_dump.pklg.zip)

**Environment:  (please complete the following information):**
 - Current BTstack branch: master
 - Bluetooth Controller [CSR 8510]
 - Remote device: [android 10 MI8]
- Ubuntu

**Additional context**

    X - disable repeat mode
    z - shuffle all tracks
    Z - disable shuffle mode
    a/A - register/deregister TRACK_CHANGED
    R/P - register/deregister PLAYBACK_POS_CHANGED

    --- Volume Control ---
    t - volume up   for 10 percent
    T - volume down for 10 percent
    ---
     - pause
    Could not perform command, status 0x c
    AVRCP Target    : Volume set to 40% (51)
    A2DP  Sink      : Stream started
    A2DP  Sink      : Stream paused
     - forward
    Could not perform command, status 0x c
     - stop
    Could not perform command, status 0x c
    CTRL-C - SIGINT received, shutting down..
    A2DP  Sink      : Stream released
    WAV Writer: Decoding done. Processed 2000 SBC frames:
     - 2000 good
     - 0 bad
    WAV Writer: Wrote 256000 audio frames to wav file: av2dp_sink_demo.wav
    AVRCP: Channel released: cid 0x01
    A2DP  Sink      : Signaling connection released

**Comment by jsplyy** [comment]
Hi @mringwal, do you know this issue?

**Comment by mringwal** [comment]
hi @jsplyy I'm not aware of the issue and only had time for a quick look at the log. It's still in the queue. The log mentions a 'wrong packet size', which might indicate the problem.

**Comment by milamikica** [comment]
Hi, we updated develop branch, could you please try it again.

**Comment by jsplyy** [comment]
Hi @mringwal , I try again with latest commits on develop branch, 
and now most commands could work, but some commands still show "Could not perform command, status 0x c"

**Comment by mringwal** [comment]
Thanks for retesting. We'll check and get back to you.

**Comment by mringwal** [comment]
That was a tricky one: the 'track changed' notification reset the state and caused the 'command disallowed'. We're reworked the notification handling and can use fast forward / stop fast forward now. Please confirm.

**Comment by mringwal** [comment]
ping?

**Comment by mringwal** [comment]
Merged onto master / no further feedback.
