### ISSUE TITLE
Rcvd Unknown 0x%08x in hci_dump.pklg

### ISSUE THREAD

**Issue by jsplyy** [bluekitchen/btstack#316]
**Describe the bug**
Rcvd Unknown 0x%08x in hci_dump.pklg

**To Reproduce**
1. Run example 'a2dp_sink_demo '

**Expected behavior**
Is it a bug here? I suppose all the event from controller should be handled.

**HCI Packet Logs**
[hci_dump_03.zip](https://github.com/bluekitchen/btstack/files/5142525/hci_dump_03.zip)

**Environment:  (please complete the following information):**
 - Current BTstack branch: develop
 - Bluetooth Controller [CSR 8510]
 - Remote device: [android 10 MI8]
- Ubuntu

**Comment by mringwal** [comment]
Hi. It's mainly a bug in Wireshark - the format string seems incorrect - it should report 'Rcv Unknown Event 0x{EVENT ID}'.
BTstack defines it own events outside of the range used by Bluetooth itself. See src/btstack_defines.h for the mapping of event code to used event.
