### ISSUE TITLE
Should this be CON_PARAMETER_UPDATE_NEGATIVE_REPLY?

### ISSUE THREAD

**Issue by thyrrestrup** [bluekitchen/btstack#323]
https://github.com/bluekitchen/btstack/blob/16f6f81ae588cf9f7d69b19328eee69fbd03db94/src/hci.c#L2773

**Comment by mringwal** [comment]
Excellent observation. Yes, it should be CON_PARAMETER_UPDATE_NEGATIVE_REPLY to let the stack reject it via HCI. Fixed in https://github.com/bluekitchen/btstack/commit/c3898ca4c0fec8c0eb3175960a2040ea4cb348a0
Thanks!
