### ISSUE TITLE
What is the limitation for dual role?

### ISSUE THREAD

**Issue by BitProgress** [bluekitchen/btstack#330]
I am running the BKSTACK in Windows environment using a CSR8510 interface.
I am running:
1. BLE peripheral, which is advertising
2. BLE central, which is scanning BLE advertising data

When I want to connect to a BLE peripheral found during scanning, the connection is failing.
If I disable BLE peripheral advertising before connecting to the BLE peripheral - it works.

Is it due to stack limitation, hardware limitation or have I configured something wrong?

BR. Martin

**Comment by mringwal** [comment]
Hi Martin

The CSR8510 does only support a single LE role at one time (so, it's a firmware limitation inside the hardware). It might be possible to send non-connectable advertisements while scanning/connecting, but that won't help with the LE Peripheral role.

You could use a Laird BT851 USB Module https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bt850-series-bluetooth-module
It supports multiple roles.

Another option is to get an nRF52840 USB dongle and flash the Zehpyr USB HCI firmware on it.
