### ISSUE TITLE
SPP counter customization 

### ISSUE THREAD

**Issue by hananabilabd** [bluekitchen/btstack#332]
I am using SPP counter example and hope to customize it just to have a simple SPP that is able to receive bytes of data. 
while debugging it always enters HAL_UART_RxCpltCallback 
![image](https://user-images.githubusercontent.com/26032494/106355858-6544ee00-6303-11eb-84d5-989c35ad9f7f.png)
I see that you are registering a timer  in one_shot_timer_setup , Does removing this line will make it act like normal SPP ?

**Comment by mringwal** [comment]
Hi

This is not an issue of the Bluetooth stack. Please post general question on the community mailing list instead. https://groups.google.com/group/btstack-dev

SPP is the profile between two Bluetooth devices. How this data is used, e.g. forwarded to a local UART, is up to the application. In the SPP Counter, the demo app just sends a heartbeat to the remote side. It does not use a local UART.

**Comment by hananabilabd** [comment]
to what remote side does it send to ? 
Is there any documentation for this example ?

**Comment by mringwal** [comment]
Well, it does send the heartbeat counter to the remote device that connects to it.
Documentation (extracted from the comments in the C file): https://bluekitchen-gmbh.com/btstack/examples/examples/index.html#spp-server-heartbeat-counter-over-rfcomm
