### ISSUE TITLE
Bluetooth connection ESP32 and headset/speaker

### ISSUE THREAD

**Issue by rrezaei2** [bluekitchen/btstack#347]
Hello,
I am looking for an arduino code to send sound signals via Bluetooth to a headset or speaker.
At the monent I am testing the ESP32 with the Jabra SPEAK 510 USB as my sink.
I couldn't find a tested code which works well. Could you please help?

Thanks!

**Comment by mringwal** [comment]
Hi. You can use the a2p_source_demo with the esp-idf and ESP32. If that doesn't work, feel free to post your issue here.

You may ask the community on the public mailing list: https://groups.google.com/group/btstack-dev
