### ISSUE TITLE
Random "idling" after multiple rfcomm connections

### ISSUE THREAD

**Issue by Matheus-Garbelini** [bluekitchen/btstack#358]
### Describe the bug
Sometimes **repeatedly** starting RFCOMM connection gets blue kitchen stuck into an active connection as if BT state machine is idle even after receiving L2CAP Configure Response from the target. The symptom is the user packet handler does not seem to receive RFCOMM_EVENT_CHANNEL_OPENED. Looking at the logs, it appears bluekitchen does not reply with `L2CAP Configure Response` when it should.

The capture below shows what happens during the hang.
![Screenshot_20210601_185510](https://user-images.githubusercontent.com/6465668/120312633-906c3800-c30b-11eb-9315-af090fa87085.png)

The over-the-air capture shows as follows:
![Screenshot_20210601_190354](https://user-images.githubusercontent.com/6465668/120313077-1f795000-c30c-11eb-8179-be166466ade2.png)

On both captures, it's visible that `L2CAP Configure Response` is not sent from bluekitchen to the target.

### To Reproduce
1. Compile the inline example below
2. Start the example with `./sdp_rfcomm_query -u /dev/ttyUSB1 -a 41:42:00:00:00:ab --iocap 3 --authreq 3 --bounding 1`
You may omit `-u` since you don't necessarily need to run this over h4.
3. The example discovers SDP services, connect to each service, and then disconnects from all.
4. This is repeated in a cycle. But at some point, the connection gets stuck as if BT state machine gets idle.

<details> 
  <summary>Inline BT code: Custom code modified from sdp_rfcomm_query.c</summary>
  
```C
#include "btstack_config.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>

#include "hci_cmd.h"
#include "btstack_run_loop.h"

#include "btstack.h"

#define NUM_SERVICES 20

int conf_iocap = SSP_IO_CAPABILITY_NO_INPUT_NO_OUTPUT;
int conf_auth_req = SSP_IO_AUTHREQ_MITM_PROTECTION_NOT_REQUIRED_GENERAL_BONDING;
int conf_enable_bounding = 1;
int conf_discoverable = 0;
char conf_pin[5] = {'0', '0', '0', '0', '\x00'};

int flag_bounding_start = 0;
int flag_bounding_done = 0;
int flag_rfcomm_connection_start = 0;
int flag_rfcomm_connection_done = 0;

int var_rfcomm_opened_channels = 0;
int var_rfcomm_closed_channels = 0;
uint16_t var_rfcom_cids[20];

static btstack_timer_source_t timer_rfcomm_query;
static btstack_timer_source_t timer_rfcomm_connection;
static btstack_timer_source_t timer_ssp_pairing;
static bd_addr_t remote_addr;

static struct
{
    uint8_t channel_nr;
    char service_name[SDP_SERVICE_NAME_LEN + 1];
} services[NUM_SERVICES];

static uint8_t service_index = 0;
static uint8_t current_service_index = 0;

static btstack_packet_callback_registration_t hci_event_callback_registration;

static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size);

static btstack_context_callback_registration_t handle_sdp_client_query_request;

static void handle_start_sdp_client_query(void *context)
{
    UNUSED(context);
    printf("Starting RFCOMM Query\n");
    sdp_client_query_rfcomm_channel_and_name_for_uuid(&packet_handler, remote_addr, BLUETOOTH_ATTRIBUTE_PUBLIC_BROWSE_ROOT);
}

static void store_found_service(const char *name, uint8_t port)
{
    printf("APP: Service name: '%s', RFCOMM port %u\n", name, port);
    if (service_index < NUM_SERVICES)
    {
        services[service_index].channel_nr = port;
        strncpy(services[service_index].service_name, (char *)name, SDP_SERVICE_NAME_LEN);
        services[service_index].service_name[SDP_SERVICE_NAME_LEN] = 0;
        service_index++;
    }
    else
    {
        printf("APP: list full - ignore\n");
        return;
    }
}

static void report_found_services(void)
{
    printf("\n *** Client query response done. ");
    if (service_index == 0)
    {
        printf("No service found.\n\n");
    }
    else
    {
        printf("Found following %d services:\n", service_index);
    }
    int i;
    for (i = 0; i < service_index; i++)
    {
        printf("     Service name %s, RFCOMM port %u\n", services[i].service_name, services[i].channel_nr);
    }
    printf(" ***\n\n");
}

static void reset_vars()
{
    flag_bounding_start = 0;
    flag_bounding_done = 0;
    flag_rfcomm_connection_start = 0;
    flag_rfcomm_connection_done = 0;
    var_rfcomm_closed_channels = 0;
    var_rfcomm_opened_channels = 0;
    service_index = 0;
}

static void start_ssp_pairing()
{
    static int started = 0;
    if (!started)
    {
        started = 1;
        // set one-shot timer
        timer_ssp_pairing.process = &start_ssp_pairing;
        btstack_run_loop_set_timer(&timer_ssp_pairing, 500);
        btstack_run_loop_add_timer(&timer_ssp_pairing);
    }
    else
    {
        started = 0;
        printf("Starting Bounding with IOCap = %02X, AuthReq=%02X\n", conf_iocap, conf_auth_req);
        gap_dedicated_bonding(remote_addr, 0);
    }
}

static void start_rfcomm_query()
{
    static int started = 0;
    static int created = 0;
    if (!started)
    {
        started = 1;
        // set one-shot timer
        timer_rfcomm_query.process = &start_rfcomm_query;
        btstack_run_loop_set_timer(&timer_rfcomm_query, 1000);
        btstack_run_loop_add_timer(&timer_rfcomm_query);
    }
    else
    {
        started = 0;
        handle_sdp_client_query_request.callback = &handle_start_sdp_client_query;
        (void)sdp_client_register_query_callback(&handle_sdp_client_query_request);
    }
}

static void start_rfcomm_connection()
{
    static int started = 0;
    if (!started)
    {
        started = 1;
        // set one-shot timer
        timer_rfcomm_connection.process = &start_rfcomm_connection;
        btstack_run_loop_set_timer(&timer_rfcomm_connection, 500);
        btstack_run_loop_add_timer(&timer_rfcomm_connection);
    }
    else
    {
        started = 0;
        if (service_index == 0)
        {
            // Try to force connection to devices without rfcomm service
            printf("Fallback, connecting to %s, RFCOMM port %u\n", services[0].service_name, services[0].channel_nr);
            rfcomm_create_channel(&packet_handler, remote_addr, services[0].channel_nr, &var_rfcom_cids[0]);
            return;
        }
        while (var_rfcomm_opened_channels < service_index)
        {
            int j = var_rfcomm_opened_channels;
            printf("Connecting to %s, RFCOMM port %u\n", services[j].service_name, services[j].channel_nr);
            int res = rfcomm_create_channel(&packet_handler, remote_addr, services[j].channel_nr, &var_rfcom_cids[j]);

            if (!res) // Create channel ok
                return;
            else
                printf("Failed with status=%d\n", res);

            var_rfcomm_opened_channels++;
        }
    }
}

static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size)
{
    UNUSED(channel);
    UNUSED(size);

    // printf("type:%d\n", packet_type);

    // HCI Events
    if (packet_type == HCI_EVENT_PACKET)
    {
        switch (hci_event_packet_get_type(packet))
        {

        case BTSTACK_EVENT_STATE:
            // BTstack activated, get started
            if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING)
            {
                // Start SDP Query
                start_rfcomm_query();
            }
            break;
        case HCI_EVENT_DISCONNECTION_COMPLETE:
            puts("HCI Disconnection received");
            printf("flag_bounding_start=%d,flag_rfcomm_connection_start=%d,flag_rfcomm_connection_done=%d\n", flag_bounding_start, flag_rfcomm_connection_start, flag_rfcomm_connection_done);
            if (flag_rfcomm_connection_done)
            {
                flag_rfcomm_connection_done = 0;
                reset_vars();
                start_rfcomm_query();
            }
            else if (flag_bounding_start)
            {
                flag_bounding_start = 0;
                start_ssp_pairing();
            }
            else if (flag_rfcomm_connection_start)
            {
                flag_rfcomm_connection_start = 0;
                start_rfcomm_connection();
            }
            else if (var_rfcomm_closed_channels < service_index)
            {
                start_rfcomm_connection();
            }

            break;
        case HCI_EVENT_PIN_CODE_REQUEST:
            // inform about pin code request
            printf("Pin code request - using %s\n", remote_addr);
            hci_event_pin_code_request_get_bd_addr(packet, remote_addr);
            // baseband address, pin length, PIN: c-string
            hci_send_cmd(&hci_pin_code_request_reply, &remote_addr, 4, conf_pin);
            break;
        case HCI_EVENT_SIMPLE_PAIRING_COMPLETE:
        {
            flag_bounding_done = 1;
            flag_rfcomm_connection_start = 1;
            uint8_t res = hci_event_simple_pairing_complete_get_status(packet);
            printf("Secure Simple Pairing complete status: %d\n", res);
            // Disconnection will be triggered automatically, altough some slaves may continue.
            if (res != 0)
            {
                reset_vars();
                flag_rfcomm_connection_done = 1;
                hci_disconnect_all();
            }
            break;
        }

        case RFCOMM_EVENT_CHANNEL_OPENED:

            // data: event(8), len(8), status (8), address (48), server channel(8), rfcomm_cid(16), max frame size(16)
            if (rfcomm_event_channel_opened_get_status(packet))
            {
                printf("RFCOMM channel open failed, status %u\n", rfcomm_event_channel_opened_get_status(packet));
            }
            else
            {
                int rfcomm_channel_id = rfcomm_event_channel_opened_get_rfcomm_cid(packet);
                int mtu = rfcomm_event_channel_opened_get_max_frame_size(packet);
                printf("RFCOMM channel open succeeded. New RFCOMM Channel ID %u, max frame size %u\n", rfcomm_channel_id, mtu);
            }
            var_rfcomm_opened_channels++;
            // Open new channel, otherwise close all, service_index 0 will force connection
            if ((var_rfcomm_opened_channels < service_index))
            {
                // Open all RFCOMM channels
                start_rfcomm_connection();
            }
            else
            {
                // Disconnect from all RFCOMM channels
                for (int i = 0; i < service_index; i++)
                {
                    rfcomm_disconnect(var_rfcom_cids[i]);
                }
                if (service_index == 0)
                {
                    flag_rfcomm_connection_done = 1;
                    hci_disconnect_all();
                }
            }

            break;
        case RFCOMM_EVENT_CHANNEL_CLOSED:
            var_rfcomm_closed_channels++;
            printf("RFCOMM channel closed, idx=%d/%d\n", var_rfcomm_closed_channels, service_index);

            if (var_rfcomm_closed_channels >= service_index)
            {
                printf("All done!\n");
                flag_rfcomm_connection_done = 1;
                hci_disconnect_all();
            }

            break;

        default:
            switch (packet[0])
            {
            case SDP_EVENT_QUERY_RFCOMM_SERVICE:
                store_found_service(sdp_event_query_rfcomm_service_get_name(packet),
                                    sdp_event_query_rfcomm_service_get_rfcomm_channel(packet));
                break;
            case SDP_EVENT_QUERY_COMPLETE:
                if (sdp_event_query_complete_get_status(packet))
                {
                    printf("SDP query failed 0x%02x, retrying...\n", sdp_event_query_complete_get_status(packet));
                    sdp_client_query_rfcomm_channel_and_name_for_uuid(&packet_handler, remote_addr, BLUETOOTH_ATTRIBUTE_PUBLIC_BROWSE_ROOT);
                }
                else
                {
                    printf("SDP query done.\n");
                    report_found_services();
                    if (!flag_bounding_done)
                    {
                        flag_bounding_start = 1;
                        hci_disconnect_all();
                    }
                }

                break;
            }
        }
    }
}

#ifdef HAVE_POSIX_FILE_IO
static void usage(const char *name)
{
    printf("\nUsage: %s -a|--address aa:bb:cc:dd:ee:ff\n", name);
    printf("Use argument -a to connect to a specific device and dump the result of SDP query for L2CAP services.\n\n");
}
#endif

void signal_handler(int signal)
{
    exit(0);
}

int btstack_main(int argc, const char *argv[]);
int btstack_main(int argc, const char *argv[])
{
    (void)argc;
    (void)argv;

    int remote_addr_found = 0;
    for (size_t i = 0; i < argc; i++)
    {
        if (argc > i + 1)
        {
            if (!strcmp(argv[i], "-a") || !strcmp(argv[i], "--address"))
            {
                remote_addr_found = sscanf_bd_addr(argv[i + 1], remote_addr);
                printf("address=%s\n", argv[i + 1]);
            }
            else if (!strcmp(argv[i], "--iocap"))
            {
                conf_iocap = atoi(argv[i + 1]);
                printf("iocap=%d\n", conf_iocap);
            }
            else if (!strcmp(argv[i], "--authreq"))
            {
                conf_auth_req = atoi(argv[i + 1]);
                printf("authreq=%d\n", conf_auth_req);
            }
            else if (!strcmp(argv[i], "--bounding"))
            {
                conf_enable_bounding = atoi(argv[i + 1]);
                printf("bouding=%d\n", conf_enable_bounding);
            }
            else if (!strcmp(argv[i], "--discoverable"))
            {
                conf_discoverable = atoi(argv[i + 1]);
                printf("discoverable=%d\n", conf_discoverable);
            }
        }
    }

    if (!remote_addr_found)
    {
        usage(argv[0]);
        exit(1);
    }

    signal(SIGTERM, signal_handler);

    // init L2CAP
    l2cap_init();
    rfcomm_init();

    // register for HCI events
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    gap_delete_all_link_keys();
    gap_ssp_set_io_capability(conf_iocap);
    gap_ssp_set_authentication_requirement(conf_auth_req);
    gap_set_bondable_mode(conf_enable_bounding);
    gap_discoverable_control(conf_discoverable);
    gap_set_local_name("BT RFCOMM 00:00:00:00:00:00");
    hci_set_inquiry_mode(INQUIRY_MODE_STANDARD);
    // hci_set_master_slave_policy(HCI_ROLE_MASTER);
    // hci_set_master_slave_policy(HCI_ROLE_SLAVE);
    // turn on!
    hci_power_control(HCI_POWER_ON);

    return 0;
}

```  
</details>

### Expected behavior
RFCOMM channel or timeout events should be forwarded to the user packet handler so we can perform some corrective actions such as reconnect. Right now, it seems that I do not get RFCOMM_EVENT_CHANNEL_OPENED to collect the status of whether the RFCOMM connection has failed or not.

### HCI Packet Logs
[debug.zip](https://github.com/bluekitchen/btstack/files/6575703/debug.zip)

This log is **special**. It has the pklg file, but also a real over-the-air capture of LMP packets so you know precisely what is happening over-the-air. Because Wireshark cannot decode this file, I provide a compiled plugin
that you install to Wireshark **C:\Program Files\Wireshark\plugins\3.4\epan**. 
I can compile this plugin for Linux Wireshark if required.
* hci_dump.pklg - Default bluekitchen log file
* capture_bluetooth.pcapng - LMP & L2CAP wireshark capture (requires h4bcm.dll)
* logs.txt - Combined logs of LMP & L2CAP packets & program output (stdout)
* stack.1.txt - Bluekicthen program output (stdout)
* session.1.txt - Only LMP & L2CAP packets
* readme_wireshark_lmp_captures.txt - Guide to install h4bcm on wireshark for windows

### Environment: 
 - Current BTstack branch: develop
 - Bluetooth Controller: ESP32 VHCI (It's a custom code that does VHCI callback to UART path, nothing fancy)
 - Remote device: Bluetrum AB32VG1 (but the bug may happen with any target)

### Additional context
I'm trying to perform a full cycle as follows:
1. Query RFCOMM SDP services
2. Perform Pairing
3. Connect to target, start encryption and open all scanned 
4. Close all RFCOMM channels and delete all keys
5. Start again

**Comment by mringwal** [comment]
Hi Matheus. Thanks for reporting - and providing the wireshark plug-ins. What would be the original tool to view these? I've got the Frontline Protocol Viewer installed.

In the screenshot, BTstack doesn't receive/log the L2CAP Configure Request from the remote - which is visible in the air trace. Any chance it got lost over the HCI Transport?

**Comment by Matheus-Garbelini** [comment]
> In the screenshot, BTstack doesn't receive/log the L2CAP Configure Request from the remote - which is visible in the air trace. Any chance it got lost over the HCI Transport?

Hi @mringwal, thanks for pointing this out. It appears to be some HCI-H4 transmission error from esp32 to pc. I may need to fix this by adding some CRC check & retransmission on my esp32 vhci-uart code.

In any case, is there some L2CAP or RFCOMM timeout event that I can receive in the packet handler whenever such random uart errors occur even if `L2CAP Configure Request` is not received from remote? The only configuration I found is related to l2cap response timeout at [l2cap.c](https://github.com/bluekitchen/btstack/blob/master/src/l2cap.c#L113). I was checking if there is a way to retry `l2cap channel configuration with remote` without forcing disconnection.

> What would be the original tool to view these? I've got the Frontline Protocol Viewer installed.

A patched esp32 firmware that exposes Espressif Internal BT Baseband TX/RX path for sniffing. The received packets are then saved to .pcapng file and can be viewed using the plugin that I've attached. I don't know Frontline Protocol Viewer, but it appears to require expensive hardware.
Hopefully, this esp32 firmware will be released to the public after some embargo process.

Thanks again for your reply.

**Comment by mringwal** [comment]
>  It appears to be some HCI-H4 transmission error from esp32 to pc. I may need to fix this by adding some CRC check & retransmission on my esp32 vhci-uart code.

> In any case, is there some L2CAP or RFCOMM timeout event that I can receive in the packet handler whenever such random uart errors occur even if L2CAP Configure Request is not received from remote? The only configuration I found is related to l2cap response timeout at l2cap.c. I was checking if there is a way to retry l2cap channel configuration with remote without forcing disconnection.

The Bluetooth protocol stack design basically assumes error-free packet transport end-to-end, with a minor exception of dropping ACL packets in the Controller under some conditions. I never actually tried that. I would argue that this is a good decision, as everything else (e.g. handling random errors on the HCI Transport) would let the complexity explode.

To make a long story short, please make sure that you don't flip a single bit between the Controller and the Host, btw. BTstack assumes that it can just pause incoming data via RTS indefinitely, although this should not be a problem when running on a desktop OS with large buffers.

Do you use the build-in HCI H4 UART of the ESP32? It sounds like you've implemented your own transport. An alternative could be to implement the H5 Protocol, which includes the full package (CRC, frame re-sync, windowing, re-transmission...).

(no, there's no retry functionality as packets either are delivered or the connection is disconnected in case of transmission problems).

> A custom esp32 firmware. The received packets are then saved to .pcapng file and can be viewed using the plugin that I've attached. I don't know Frontline Protocol Viewer, but it appears to require expensive hardware.
Hopefully, this esp32 firmware will be released to the public after some embargo process.

Wow! That would be awesome. I don't have a full featured BR/EDR sniffer either. I did implement an LE Sniffer (https://github.com/bluekitchen/raccoon), but LE is rather simple and there are others too. 

I'm closing this ticket, but feel free to contact me directly for news on your sniffer - matthias@bluekitchen-gmbh.ocm

**Comment by Matheus-Garbelini** [comment]
Hi @mringwal thanks for your reply. 
Indeed since it assumes error-free, this issue should not require fixes from your side.
However, I was hoping there were some internal timeouts I could use to work around an H4 error scenario.

> Do you use the build-in HCI H4 UART of the ESP32? It sounds like you've implemented your own transport. An alternative could be to implement the H5 Protocol, which includes the full package (CRC, frame re-sync, windowing, re-transmission...).

It's my custom transport, but it's really just an ESP32 VHCI callback forwarding H4-HCI packets to UART.
I'll then add some CRC check + retry since I don't need anything fancy like H5. 
For now, I'll add a manual timer once an l2cap connection has been established as a timeout workaround for l2cap configuration issues.

> I'm closing this ticket, but feel free to contact me directly for news on your sniffer - matthias@bluekitchen-gmbh.ocm

Sure, I'll let you know. For some reason, BR/EDR vendors may use some obscure or expensive sniffers. 
Not sure why this is the case even in 2021.

**Comment by mringwal** [comment]
> It's my custom transport, but it's really just an ESP32 VHCI callback forwarding H4-HCI packets to UART.
I'll then add some CRC check + retry since I don't need anything fancy like H5.
For now, I'll add a manual timer once an l2cap connection has been established as a timeout workaround for l2cap configuration issues.

Hm...how did you connect the ESP32 UART to your PC? If you use a regular dev kit with some USB-2-UART (e.g. FTDI232), the UART traces are a few centimeters and the chance for errors there are close to zero. Also, in the case of random communications errors, they would happen at others times too, e.g. during init. Could you check if your forwarding code can operate full-duplex? L2CAP Config is the first time whee there's full duplex communication usually. (I've seen similar issues with custom BTstack ports to MCUs). A quick check with a logic analyser might be helpful, too.,

> Sure, I'll let you know. For some reason, BR/EDR vendors may use some obscure or expensive sniffers.
> Not sure why this is the case even in 2021. I'm guessing it's due to some licensing issues in releasing LMP tools to the public.

Well, the really good ones are 80 Mhz SDR implementations, which are still not cheap. (I bought a LimeSDR Mini with 30 Mhz bandwidth, but if you don't have the full 80 Mhz, you would need to change the range, which requires FPGA code..). I don't think I've seen a RF chip that implements BR/EDR on the physical level - not like the easy to use nRF5x.

All link layers for regular Bluetooth Controllers are closed-source, and often licensed from a third-party, so there are licensing issues as you point out as well.

**Comment by Matheus-Garbelini** [comment]
@mringwal Hi,
Sorry for the late reply. The **_active_** sniffer is now available in the following link:
https://github.com/Matheus-Garbelini/esp32_bluetooth_classic_sniffer

You can sniff Baseband packets directly from ESP32 when connecting (or accepting connection) to a remote BT device.
The project uses _Bluekitchen_ out of the box to guide the BT host protocol exchanges. Plus you can get packets in both Scapy or Wireshark live view.

Let me know what you think :+1:

**Comment by mringwal** [comment]
@Matheus-Garbelini Thanks for the hint. I've seen the BrakTooth report and had a look at your repo, which didn't have a Readme. The new Readme looks great, I'll try to try it out soon.. and will provide feedback of course. Thanks!

**Comment by Matheus-Garbelini** [comment]
@mringwal thanks. Yes I actually had to rush with the first commit, but now proper documentation with all acknowledgements are there. Didn't test with macOS yet, but my plan is to make sure the sniffer can be used on all platforms including Windows and macOS. Feel free to provide any feedback when also testing under macOS.

Regards.
