### ISSUE TITLE
failed to open file /tmp/hci_dump.pklg, errno = 2

### ISSUE THREAD

**Issue by gitdreambox** [bluekitchen/btstack#368]
W10+MinGW64 

winpty ./spp_and_gatt_counter.exe
BTstack/windows-winusb booting up
failed to open file /tmp/hci_dump.pklg, errno = 2
Packet Log: /tmp/hci_dump.pklg

**Comment by mringwal** [comment]
Thanks for the hint. On Windows, /tmp only exists when using msys64. I've updated all Windows ports to use the current directory. Please switch to develop branch.
