### ISSUE TITLE
Failed to connect to a2dp_source_demo

### ISSUE THREAD

**Issue by alisagao123** [bluekitchen/btstack#374]
**Describe the bug**
AuthenticationTimeout to connect to a2dp_source_demon sometimes, as below:
Attempting to pair with 00:1A:7D:DA:71:11
Failed to pair: org.bluez.Error.AuthenticationTimeout

**To Reproduce**
1. Run example 'a2dp_source_demo'
2. Connect from remote device(linux system) with bluetoothctl app
***Note*** there are two "a2dp_source_demo" running in one LAB room, but they run on different PCs(Linux system)
one is : 00:1A:7D:DA:71:11; another is "00:1A:7D:DA:71:13". not sure if this is the reason.
********************************
**HCI Packet Logs**
[steps_logs.txt](https://github.com/bluekitchen/btstack/files/6943275/steps_logs.txt)

**Expected behavior**
it should connect to a2dp source demo even several times tries.

**Environment:  (please complete the following information):**
1. Current BTstack branch: [develop]
2. Bluetooth Controller [biaze D27]
3. Remote device: embedded device running Linux 5.10

**Comment by mringwal** [comment]
Hi. Please enable hci packet logging and convert the text output into a .pklg file which can be viewed with Wireshark.
See: https://bluekitchen-gmbh.com/btstack/#how_to/#bluetooth-hci-packet-logs

Do you have a datasheet for the [biaze D27] Bluetooth Controller?

**Comment by alisagao123** [comment]
@mringwal , thanks for your reply, I will get the packet as your request.
and I found another issue:
when I plug-out/plug-in the BT dongle, and use command "hciconfig -a", I can see the interface up and running, 
but after I run the "a2dp_source_demo", and then this interface disappear in command "hciconfig -a", do you known why or is it expected?

(base) elbert@shrek-ThinkCentre-M83:~$ hciconfig
hci0:	Type: Primary  Bus: USB
	BD Address: 00:1A:7D:DA:71:11  ACL MTU: 310:10  SCO MTU: 64:8
	UP RUNNING 
	RX bytes:646 acl:0 sco:0 events:42 errors:0
	TX bytes:2175 acl:0 sco:0 commands:42 errors:0

(base) elbert@shrek-ThinkCentre-M83:~$ sudo a2dp_source_demo 
[sudo] password for elbert: 
Packet Log: /tmp/hci_dump.pklg
USB Path: 01-03
Local version information:
- HCI Version    0x0006
- HCI Revision   0x22bb
- LMP Version    0x0006
- LMP Subversion 0x22bb
- Manufacturer 0x000a
BTstack up and running on 00:1A:7D:DA:71:11.

[2]+  Stopped                 sudo a2dp_source_demo
(base) elbert@shrek-ThinkCentre-M83:~$ hciconfig
(base) elbert@shrek-ThinkCentre-M83:~$

**Comment by mringwal** [comment]
When you use BTstack with the USB Bluetooth dongle, you should not use it with BlueZ at the same time. I don't know BlueZ very well, in the libusb/Readme.md, I've added notes on how to prevent BlueZ / Kernel from using the USB Dongle. 

Ah... so after running BTstack it is not bad that it does not appear in hciconfig. (you shouldn't even use it with BlueZ at all)

**Comment by mringwal** [comment]
No response, closing this.
