### ISSUE TITLE
HCI Events decoding questions

### ISSUE THREAD

**Issue by AlexanderSveshnikov** [bluekitchen/btstack#375]
Hello. 
I made my project on the base of "HID keyboard example" using esp32. Some hosts connects with my device, some hosts not. So I decided to decode HCI events in a hope to find problems using "Bluetooth Specification v4 Vol.2 Part E, 7.7 Events" document. My First question is about "IO Capabilities response" (Event id 0x32). I found following packet data: 32 09 83 C8 41 DA 45 00 01 00 03. 
09 - length
83 C8 41 DA 45 00 - bd address
01 - IO Capability  - DisplayYesNo ?
00 - OOB authentication data not present
03 - Authentication_Requirements - MITM Protection Required – Dedicated Bonding. Use IO Capabilities
to determine authentication procedure
Is it right to set IO Capability to "DisplayYesNo"? Maybe it's better to use "KeyboardOnly" (02)? How can I change it?
How  can I change "Authentication_Requirements" field (I think I need "MITM Protection Not Required – General Bonding. Numeric Comparison with automatic accept allowed" (04 instead of 03)

**Comment by mringwal** [comment]
Hi. You can convert the hci dump into a pklg file using tool/create_packet_log.py and analyse it in Wireshark.
Please ask general questions on the bstack mailing list. (please see gap_ssp_... on how to configure Classic SSP)
