### ISSUE TITLE
How to test libusb demo

### ISSUE THREAD

**Issue by donny681** [bluekitchen/btstack#377]
**Problem**
I want to know how btstack libusb example connect to usb device,but I don't know the usb path for a2dp_demo.It always show that the usb path is wrong.

**LOG**
/nfs/btstack # lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0bda:d723 Realtek Semiconductor Corp.

**Comment by mringwal** [comment]
Hi. The readme has hints on how to prevent the OS / BlueZ from accessing an USB Bluetooth Controller. 

On the other hand, most Realtek controllers require some firmware to be loaded upon boot, which BTstack does not support. Please try with an extern USB Bluetooth dongle, with an CSR 8510 or Broadcom/Cypress controller.
