### ISSUE TITLE
Service Change - BLE

### ISSUE THREAD

**Issue by tamarva** [bluekitchen/btstack#385]
We have a gatt peripheral, we want to support DB change across application version (both mobile iOS and Android connects to us). 
for that we considered both service changed and hash characteristic. 
service changed should support indicate according to documentation. but btstack only defines read.  
Is service changed supported in btstack? 
using hash characteristic also did not work (perhaps ios does not support it?)
your help is much appreciated

**Comment by tamarva** [comment]
Hi, 
Regrading the hash characteristic - I added it to the .gatt file. The iOS device still tried to reach the wrong handles.
Is it supported in iOS or should we implement anything?

Regrading the service change characteristic - 
We looked in the examples and saw it only had read property.

Also, why would the server need to store which version of it's db has been used by each client? Why can't it just notify to all it's clients when there's a change?
When sending a notification of service change, do we need to implement anything in iOS or it supports cleaning it's caching when receiving this notification.

Thank you!

**Comment by mringwal** [comment]
H again
I just checked and we dropped the  GATT Service Changed Characteristic  from all examples in Jan 2020. The idea is that if you don't have that one, the remote device cannot cache the DB. If you have it, the remove can cache it and expects your device to tell you when it has changed. Now, after a reboot when a bonded device connects and registers for notifications: do you send a DB changed or not? For this you need to store which device use which version - or just send it every time - but then you can just skip the Characteristic.

While we've tested the GATT Database Hash Characteristic against PTS, we did not try/test with iOS. The idea would be that the GATT Client stores the DB Hash and to check if it has changed on reconnect to invalidate the cached DB.
In general, it's probably easier not to modify your GATT DB.

For commercial support to help with your product, please get in touch at contact@bluekitchen-gmbh.com

**Comment by mringwal** [comment]
HI there. Have you been able to resolve your issue?
