### ISSUE TITLE
doc/manual build error

### ISSUE THREAD

**Issue by Roger-Hoo3** [bluekitchen/btstack#386]
**Describe the bug**
error occur in Makefile:69 when make in doc/manual

**To Reproduce**
make in doc/manual

**Expected behavior**
no error

**HCI Packet Logs**
NO

**Environment:  (please complete the following information):**
NO

**Additional context**
Tables is chaotic in btstack_gettingstarted.pdf, I think it is related with building error
![issue](https://user-images.githubusercontent.com/5591690/140474266-08b73a44-0014-4ac7-b4a2-d34a9c16a93b.png)

**Comment by milamikica** [comment]
Hi,

thank you for reporting this, I’ll take a look at it - for now please use the HTML version. 

Best regards,
Mila

**Comment by Roger-Hoo3** [comment]
rootcause: columnwidth is mistakenly set for longtable during converting from btstack_generated.md to btstack_final.tex by pandoc, as follows：
![image](https://user-images.githubusercontent.com/5591690/154251283-daa8919f-803c-42fe-8452-593e9b08a6b2.png)

if set columnwidth as ' {\raggedright\arraybackslash}p{0.4231\columnwidth }',  table isnot chaotic.

Now i cannot provide solution to fix this bug, perhaps it is ok which add --filter option to modify columnwidth setting during using pandoc...

**Comment by Roger-Hoo3** [comment]
this issue is related to build environment, so close it.
