### ISSUE TITLE
Can't see my device changed name in advertisement report

### ISSUE THREAD

**Issue by tamarva** [bluekitchen/btstack#388]
Hi,
i updated the version of btstack and I'm having the following issue: the behavior I should see : writing to a certain characteristic should change the device name and address. when I scan my device in the first time I can see my device. After the write - when I look at application LightBlue **I can see the new name** of the device and it's **new address** but the in the advertisement_report_contains_name method I can't see the new name of the device but only the old name (Although it clearly changed as I can see in lightblue and it worked for me before I updated the btstack)

Your help is much appreciated

**Comment by tamarva** [comment]
I fixed this by changing in the scan parameters from passive scanning to active scanning

**Comment by tamarva** [comment]
I'm not sure why but it got fixed by changing in the scan parameters from passive scanning to active scanning

**Comment by mringwal** [comment]
In BLE, the device name can be provide in the advertisement and as a GATT Characteristic of the GAP Service. Smartphone usually will first use the name from the adv if available and on connect, read the GAP Name Characteristic. Maybe your smartphone did delete the cached entry
