### ISSUE TITLE
help with HID braille for open source devices for people with disabilities

### ISSUE THREAD

**Issue by discapacidad5** [bluekitchen/btstack#389]
Hello, I am developing a device for people with disabilities. I need to use the HID braille protocol but I am not getting anything with HID for esp32, could you help me with a sample code of how I can implement the HID braille protocol?

here are references to HID braille

https://usb.org/sites/default/files/hutrr78_-_creation_of_a_braille_display_usage_page_0.pdf

https://github.com/nvaccess/nvda/blob/00cd67b737bc5b23a6f5e31cf28110b64ebf2fee/devDocs/hidBrailleTechnicalNotes.md

my repository is the following
https://github.com/brailletouch/Brailletouch

**Comment by mringwal** [comment]
Hi @discapacidad5. I haven't worked with HID Braille and have no sample code. If you have such a device, you can have a look at its HID Descriptor, but there's also one in the linked files. You can start with that one. Do common OS like mac or Windows have built-in support for these? If you're lucky, you should get HID reports to setup the braille segments. Feel free to discuss your project on the BTstack developer mailing list, but I can only help with general questions or actual issues. Good luck.
