### ISSUE TITLE
If peer l2cap connect request received before read encrption key size response, stack will be re-authenticate again and link will be failed

### ISSUE THREAD

**Issue by nick1zhao** [bluekitchen/btstack#397]
**Describe the bug**
If peer l2cap connect request received before read encrption key size response, stack will be re-authenticate again and link will be failed

**To Reproduce**
1. Run example '...'
2. Connect to/from remove device '...'
3. Start action '...'

**Expected behavior**

**HCI Packet Logs**
For all Bluetooth issues, please provide a full packet log that includes initial pairing. You need to zip the packet log as GitHub does not know how to handle .pklg files. 

How to get packet log depends on the port:
- For desktop ports, full packet logging is enabled by default and the packet log is available as `/tmp/hci_dump.pklg` (Mac/Linux), or `hci_dump.pklg' (Windows).
- For embedded ports, you can enable #define LOG_INFO in btstack_config.h and uncomment the call to 'hci_dump_init(..)' in the main() function to enable logging over UART Console or Segger RTT. Please capture text output and process using `btstack/tool/create_packet_log.py`. The tool will generate the text file into a .pklg file which can be analysed with Wireshark or Apple's PacketLogger tool.
- For ESP32: BTstack's `port/esp32/integrate.py` script copies the current version of BTstack into the esp-idf folder. To enable packet logging, you need to edit esp-idf/components/btstack/main.c

**Environment:  (please complete the following information):**
 - Current BTstack branch: [e.g. develop]
 - Bluetooth Controller [e.g. CSR 8510, TI CC2564C, ...]
 - Remote device: [e.g. iPhone X with iOS 13.3]

**Additional context**

**Comment by mringwal** [comment]
Hi. BTstack triggers authentication after encryption complete for BR/EDR Legacy Connections (non SC) to reduce/avoid risk from BIAS attacks - that's the expected behaviour. The link shouldn't fail, though. Does this happens every time, or is it some kind or race condition?

What Bluetooth Controller do you use? What Bluetooth Controller/Stack is running on the remote side?
Could you provide HCI logs? Incoming connections work for me. Without logs and without being able to reproduce, there's no much we can do.

**Comment by nick1zhao** [comment]
Hi,


HCI log as attached.&nbsp; Test device is iPhone 7 (iOS 14.2)


Controller is ourself which based on RW 5.2 IP




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bluekitchen/btstack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bluekitchen/btstack] If peer l2cap connect request received before read encrption key size response, stack will be re-authenticate again and link will be failed (Issue #397)





 
Hi. BTstack triggers authentication after encryption complete for BR/EDR Legacy Connections (non SC) to reduce/avoid risk from BIAS attacks - that's the expected behaviour. The link shouldn't fail, though. Does this happens every time, or is it some kind or race condition?
 
What Bluetooth Controller do you use? What Bluetooth Controller/Stack is running on the remote side?
 Could you provide HCI logs? Incoming connections work for me. Without logs and without being able to reproduce, there's no much we can do.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mringwal** [comment]
Hi Nick. I don't see the log attached here, could you check on GitHub Issue tracker that it's there (looks like attachments won"t work for email replies)?
You may send it to me as well matthias@bluekitchen-gmbh.com

**Comment by mringwal** [comment]
Hi Nick. Have you been able to resolve this somehow? I was not able to open your logs with Front Line's "View CFA" tool..

**Comment by mringwal** [comment]
Timeout
