### ISSUE TITLE
BTStack GPS: Not transmitting (faked) location to applications

### ISSUE THREAD

**Issue by albrechtf** [bluekitchen/btstack#4]
I am not sure if this is the right issue tracker for BTStack GPS, so please feel free to tell me where else to post this:

First of all, I just have purchased BTStack GPS, so it is not a licensing issue.

Scenario: My Flight Simulator shall send its GPS position via bluetooth to the iPad 2 WiFi Only (iOS 8.1.2), to be able to use real iPad aviation software for training purposes.
So I set up the Flight Simulator to send NMEA data to a virtual COM port, which in turn is served as Bluetooth service using Franson GpsGate.

On the iPad, BTStack GPS connects just fine via bluetooth to the PC, and retrieves the correct FS GPS position. This position, of course, differs heavily from my real location.

Unfortunately, the iPad only seems to serve location data when switching WiFi on. The WiFi based location is quite accurate, and THIS location is what is presented to all location based applications, not the BTStack received one.

I also tried switching the "Fake 1m accuracy" option on, and restarted the iPad several times. After a reboot, when starting BTStack GPS, it seems to work for the very next application to be opened, but after switching to another application (and then back to the first one), the location again is the WiFi based (real) one.

When disabling WiFi, location services are not available at all on the iPad 2 WiFi Only...

Another app, "Fake GPS", does not have any problems to fake my location for all application - it works fine (but only uses a single static location).

**Comment by mringwal** [comment]
Hi. This is for issues related to BTstack running on embedded systems.

Please try the latest version of BTstack GPS from Cydia - I can use Maps on an iPod Touch 5G with Wifi disabled.
