### ISSUE TITLE
hci packet handler

### ISSUE THREAD

**Issue by tamarva** [bluekitchen/btstack#405]
Hi,
I have a device which plays a role as both gatt server and gatt client using BLE.
In my app, I register two hci packet handlers. In the connection where my device is the server, i do certain stuff which i need to be able to separate in the other case(where the device is the client). For example, if my device in certain circumstances connected to a server(now behaves as a client), if i go into a connected event case in the packet handler, i need to know to distinguish between the cases (Or for example, if my device disconnect from the server device, i don't want it to affect the other connection). How can I distinguish between packets I receive in the packet handler?(if i received it due to my first connection or the second one)

Thanks

**Comment by mringwal** [comment]
hi @tamarva That's more suitable for our mailing list. There's no magic bullet, but it should be possible to resolve this. 

When there's an LE Connection Complete it's either an incoming connection or you have triggered it, so you will know for a specific connection handle if it's incoming or outgoing.

Next, there's GATT Client / Server. If you perform any requests via the gatt client API, you know that the response is for the client role. If you get ATT read/write requests it was triggered by the remote side and you're in the GATT Server role. 

With LE, you shouldn't receive packets without a connection handle. If you're using LE Data Channels (aka connection oriented channel with credit based flow control), you get the channel ID that was also given in the connection complete.

Anything missing?

**Comment by tamarva** [comment]
Hi,
Thanks for your help.
I'm not using LE data channels.

The thing is, i don't know which connection happens first (if i first act
as the server or as the client) - thus for example, if my device behaves
currently as client and connected to a server, i find myself go to case
ATT_EVENT_CONNECTED, and i don't know by the connection handle that i'm
currently the client!
*if i knew that at the first place my device acts as the server then yes,
i'd save the connection handle, and i'll know to distinguish between the
cases*

so there has to be something in the packet itself that would help me...

Thanks again!

**Comment by tamarva** [comment]
Hi
I think ill use HCI_LE_CONNECTION_COMPLETE which seems to solve my problem
here
Thank you!

בתאריך יום ב׳, 14 בפבר׳ 2022, 14:59, מאת Tamar Vaitzman ‏<
***@***.***>:

> Hi,
> Thanks for your help.
> I'm not using LE data channels.
>
> The thing is, i don't know which connection happens first (if i first act
> as the server or as the client) - thus for example, if my device behaves
> currently as client and connected to a server, i find myself go to case
> ATT_EVENT_CONNECTED, and i don't know by the connection handle that i'm
> currently the client!
> *if i knew that at the first place my device acts as the server then yes,
> i'd save the connection handle, and i'll know to distinguish between the
> cases*
>
> so there has to be something in the packet itself that would help me...
>
> Thanks again!
>
>
>
>
> On Sun, Feb 13, 2022 at 8:33 PM Matthias Ringwald <

**Comment by mringwal** [comment]
Glad you were able to sort it out.

FWIW ATT_EVENT_CONNECTED is emitted by att_server when it gets a HCI_LE_CONNECTION_COMPLETE, so ATT_EVENT_CONNECTED indicates that remote device has initiated the connection.

**Comment by tamarva** [comment]
Thank you!
it could also help..
I have a packet handler which I register to* both  hci events and att
server*, and when my device acted as the client (initaited the connection)
and connected, i got both into ATT_EVENT_CONNECTED and
HCI_LE_CONNECTION_COMPLETE so looks like that ATT_EVENT_CONNECTED was not
emitted.
