### ISSUE TITLE
gap_whitelist_add causes scan start/stop loop 

### ISSUE THREAD

**Issue by amorniroli** [bluekitchen/btstack#417]
**Describe the bug**
I'd like to filter out advertising report using the whitelist feature.

Adding a device address to whitelist (using gap_whitelist_add function) and then starting a scan (gap_set_scan_params function with scanning_filter_policy set to '1') causes hci_run_general_gap_le to continuosly start & stop scan because 'scanning_uses_whitelist' is always set to 'true' (hci.c file, line 4449, tag 1.5.1)

```
#ifdef ENABLE_LE_CENTRAL
    // scanning control
    if (hci_stack->le_scanning_active) {
        // stop if:
        // - parameter change required
        // - it's disabled
        // - whitelist change required but used for scanning
        // - resolving list modified
        bool scanning_uses_whitelist = (hci_stack->le_scan_filter_policy & 1) == 1;
        if ((hci_stack->le_scanning_param_update) ||
            !hci_stack->le_scanning_enabled ||
            scanning_uses_whitelist ||
            resolving_list_modification_pending){

            scanning_stop = true;
        }
    }
#endif
```

**To Reproduce**

1. Run example gap_le_advertisements.c with these changes (see also attached file):

```
static void gap_le_advertisements_setup(void){
    // Active scanning, 100% (scan interval = scan window)
    gap_set_scan_params(1,48,48, 1); // scan filter policy
    gap_start_scan(); 

    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);
}

int btstack_main(void)
{
    bd_addr_t addr;

    addr[0] = 0x02;
    addr[1] = 0x80;
    addr[2] = 0xe1;
    addr[3] = 0x00;
    addr[4] = 0x02;
    addr[5] = 0xf5;

    gap_whitelist_add (BD_ADDR_TYPE_LE_PUBLIC, addr);

    gap_le_advertisements_setup();

    // turn on!
    hci_power_control(HCI_POWER_ON);
        
    return 0;
}

```
[gap_le_advertisements.zip](https://github.com/bluekitchen/btstack/files/8716356/gap_le_advertisements.zip)

2. Run the example

**Expected behavior**
I'd expect to see the scan command being execute just one.

**HCI Packet Logs**
[hci.zip](https://github.com/bluekitchen/btstack/files/8716371/hci.zip)

**Environment:  (please complete the following information):**
 - https://github.com/bluekitchen/btstack/releases/tag/v1.5.1
 - Nucleo-L476RG + X-NUCLEO-BNRG2A1 (BlueNRG2) by ST (firmware compiled w/ LL_ONLY flag, anyway I think this is not related to controller)

**Additional context**
From my understanding, calling scan w/ filter policy cause flag scanning_uses_whitelist to be always set to 'true' because of 

```
#ifdef ENABLE_LE_CENTRAL
    // scanning control
    if (hci_stack->le_scanning_active) {
        // stop if:
        // - parameter change required
        // - it's disabled
        // - whitelist change required but used for scanning
        // - resolving list modified
        bool scanning_uses_whitelist = (hci_stack->le_scan_filter_policy & 1) == 1;
        if ((hci_stack->le_scanning_param_update) ||
            !hci_stack->le_scanning_enabled ||
            scanning_uses_whitelist ||
            resolving_list_modification_pending){

            scanning_stop = true;
        }
    }
#endif
```

scanning_uses_whitelist  is never cleared.

Scan is then stopped and started again (loop) because of 

```
#ifdef ENABLE_LE_CENTRAL
    // re-start scanning
    if ((hci_stack->le_scanning_enabled && !hci_stack->le_scanning_active)){
        hci_stack->le_scanning_active = true;
        hci_send_cmd(&hci_le_set_scan_enable, 1, 0);
        return true;
    }
#endif
```

Is this a bug or I'm doing something wrong?

Alessandro

**Comment by mringwal** [comment]
Hi @amorniroli. Thanks for reporting and the excellent issue. You probably aren't doing anything wrong :)

Could you please switch to the current develop branch and verify if the bug has been fixed there? I remember fixing a similar issue recently.
