### ISSUE TITLE
Use other eSCO configuration parameters if AUDIO is not established

### ISSUE THREAD

**Issue by amorniroli** [bluekitchen/btstack#424]
**Is your feature request related to a problem? Please describe.**
Hi,

I'm testing HFP gateway (hfp_ag_demo.c) w/ HeadSet SENA20s.

After established connection to headset, I'm trying to establish AUDIO connection without success (Audio connection establishment failed with status 28 -> ERROR_CODE_SCO_INTERVAL_REJECTED).

Debugging the code, I've noticed that the headset is not supporting the eSCO S4 configuration parameters (AT+BRSF=62, so eSCO S4 Settings Supported bit is '0'). The function **_hfp_next_link_setting_** then is iterating till it finds a valid set of configuration parameters (HFP_LINK_SETTINGS_S3 in this case), but I guess this is not supported by the headset.

At this point, there is no chance to establish audio with other settings. Forcing to use HFP_LINK_SETTINGS_S1 from debugger  the AUDIO can be established successfully.

**Describe the solution you'd like**
I'm not sure if it's a real problem or just a problem of this particular headset. From my understanding from BT HFP profile documentation, the safe settings S1 should be tried in this case (I think I'm not using 'secure connection', but I have to investigate deeper the log).

![image](https://user-images.githubusercontent.com/4875195/171021102-1f8a7dc1-5c3c-4a78-980f-de0c5ff290cc.png)

I think the best should be to try inside btstack all possible configurations in case of connection rejected.

**Describe alternatives you've considered**
Alternatively, the different configurations could be tried by user in event callback, if audio is not established.

**HCI Packet Logs**

I'm using CC2564 w/ STM32 Nucleo board.

- [hci_error.txt](https://github.com/bluekitchen/btstack/files/8799439/hci_error.txt) (Audio connection establishment failed with status 28 -> HFP_LINK_SETTINGS_S3)
- [hci_ok.txt](https://github.com/bluekitchen/btstack/files/8799436/hci_ok.txt) (Audio connection established with SCO handle 0x0101. -> HFP_LINK_SETTINGS_S1)

**Comment by mringwal** [comment]
Hi @amorniroli BTstack currently ignores the BR/EDR Secure Connection used/not used information and (should) go through the settings one by one. So if S4 fails, it should try S3, then S2, then S1.. .

In your log, the next setting isn't tried. Comparing the error 0x1c with the code, it isn't marked for retry.

I've update the code on develop branch. Could you update to current develop branch and try again?

When providing logs, please disable ENABLE_DEBUG as it's most useful when enabled for a single file.

**Comment by amorniroli** [comment]
Hi @mringwal ,

sorry fo

> When providing logs, please disable ENABLE_DEBUG as it's most useful when enabled for a single file.

I will next time: sorry for that.

> I've update the code on develop branch. Could you update to current develop branch and try again?

Thank you very much. Now w/ SENA 20s it's working as expected.

However, another headset (Cardo PACKTALK bold) is refusing to establish audio

> [00:00:09.724] LOG -- hfp.c.776: (e)SCO Connection failed 0x1a
> Audio connection establishment failed with status 26

Also 'ERROR_CODE_UNSUPPORTED_REMOTE_FEATURE_UNSUPPORTED_LMP_FEATURE' should be taken in consideration in the switch case? Adding it, it works as expected

P.S. FYI, sm.c is not compiling (row 1085)

**Comment by mringwal** [comment]
Hi @amorniroli Thanks for confirm and the feedback. I've added ERROR_CODE_UNSUPPORTED_REMOTE_FEATURE_UNSUPPORTED_LMP_FEATURE and also fixed the compile error for the case when log_debug is enabled.
