### ISSUE TITLE
ENABLE_LOG_DEBUG fails to build

### ISSUE THREAD

**Issue by kenrabold** [bluekitchen/btstack#427]
**Describe the bug**
There is a typo in src/ble/sm.c that fails to build when ENABLE_LOG_DEBUG is defined

**To Reproduce**
#define ENABLE_LOG_DEBUG
Make a build

fails here:
log_debug("sm_key_distribution_all_received: received 0x%02x, expecting 0x%02x", setup->sm_key_distribution_received_set, **_bution_expected_set_**);

should be:      
log_debug("sm_key_distribution_all_received: received 0x%02x, expecting 0x%02x", setup->sm_key_distribution_received_set, **_setup->sm_key_distribution_expected_set_**);

**Comment by mringwal** [comment]
hi @kenrabold Thanks for reporting, that's correct. We've fixed this issue on the develop branch which will be merged onto master in the enxt days.
