### ISSUE TITLE
quick question:

### ISSUE THREAD

**Issue by jnorthrup** [bluekitchen/btstack#440]
are MAC 48-bits within header CRC in all versions of transmission?

**Comment by mringwal** [comment]
Could you be more specific? 

PAN/BNEP that transmit Ethernet frames contain src and dest mac addresses, but there's also 'compression' mechanism which allow to not send the addresses of both sides as they are known.

In the Bluetooth radio transmission, I don't think the full BD_ADDR (equivalent to MAC address) is only send in connection requests as far as I know. Feel free to ask on the mailing list.

**Comment by mringwal** [comment]
Interesting. If you get old Bluetooth modules, you could use them in an RFID use case. Bluetooth Inquiry isn't particularly fast. Again, I don't remember the details on inquiry / inquiry scan. As far as I know, all data radio packets use some for of CRC, Bluetooth Classic uses crc-16 for exchanged data.
