### ISSUE TITLE
Connection to a2dp_sink while already connected to other device.

### ISSUE THREAD

**Issue by robrechtbisschop** [bluekitchen/btstack#442]
This is more of a question then an issue report.

I am using the a2dp_sink example to stream audio to my device, and want to handle following scenario:
- Device A is connected and is streaming audio to the sink
- Device B is not connected, but initiates a connection to the sink on request of the user
- Device B has previously been succesffuly paired

How would the stack handle this? Can both devices connect at the same time and is the playback source selected based on the last active stream? Or is device A automatically disconnected when device B connects by the stack? Or does the connection state need to be handled outside of the stack?

Thanks.

**Comment by mringwal** [comment]
Please discuss general topics on the mailing list. 

The stack has no limitations in this regard and can handle multiple A2DP Streams in parallel. Bluetooth resp. the Bluetooth Controller has limitations on how much traffic it can schedule. 

if you want/need to handle multiple connections, it seems to be called 'Multi-point' for headsets nowadays, this needs to be handled by the application (e.g. a2dp_sink_demo), which could try to send AVRCP Pause when the second device starts streaming audio.
