### ISSUE TITLE
l2cap.c doesn't build cleanly if ENABLE_CLASSIC is not defined on develop

### ISSUE THREAD

**Issue by peterharperuk** [bluekitchen/btstack#451]
**Describe the bug**

I took ENABLE_CLASSIC out of my btstack_config.h to built it just for BLE and I get the following build warnings. It seems to work despite this but it's not totally obvious what the "proper" fix is. I'm testing the tip of the "develop" branch.

/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c: In function 'l2cap_ertm_create_channel':
/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c:665:49: warning: implicit declaration of function 'l2cap_security_level_0_allowed_for_PSM' [-Wimplicit-function-declaration]
  665 |     const gap_security_level_t security_level = l2cap_security_level_0_allowed_for_PSM(psm) ? LEVEL_0 : gap_get_security_level();
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c:687:9: warning: implicit declaration of function 'l2cap_handle_connection_complete'; did you mean 'l2cap_send_connectionless'? [-Wimplicit-function-declaration]
  687 |         l2cap_handle_connection_complete(conn->con_handle, channel);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         l2cap_send_connectionless
/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c:690:13: warning: implicit declaration of function 'l2cap_handle_remote_supported_features_received' [-Wimplicit-function-declaration]
  690 |             l2cap_handle_remote_supported_features_received(channel);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c: In function 'l2cap_ertm_accept_connection':
/home/peterh/source/pico/pico-sdk2/lib/btstack/src/l2cap.c:733:13: warning: implicit declaration of function 'l2cap_handle_information_request_complete' [-Wimplicit-function-declaration]
  733 |             l2cap_handle_information_request_complete(connection);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**To Reproduce**

Build l2cap.c with ENABLE_CLASSIC removed on the "develop" branch.

**Expected behavior**

Common, or ble code shouldn't call classic only code.

**HCI Packet Logs**
n/a?

**Environment:  (please complete the following information):**
 - Current BTstack branch: develop
 - Bluetooth Controller infineon cyw43439
 - Remote device: n/a

**Additional context**

**Comment by mringwal** [comment]
Looks like an invalid configuration. l2cap_ertm_create_channel and l2cap_ertm_accept_connection  are only defined with ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE. However, it requires ENABLE_CLASSIC.
Please remove ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE in your config file, too, then.

I've pushed a commit on develop that throws a #error for this combination..

**Comment by peterharperuk** [comment]
Thanks!
