### ISSUE TITLE
Links on https://bluekitchen-gmbh.com/btstack/#profiles/ at least for HID are wrong

### ISSUE THREAD

**Issue by daveHitchman** [bluekitchen/btstack#460]
**Describe the bug**
Documentation bug, links arent all correct.

**To Reproduce**
 Go to https://bluekitchen-gmbh.com/btstack/#profiles/
Find the HID section
Try any of the links provided.

Example the Hid keyboard demo link is 
https://bluekitchen-gmbh.com/btstack/#profiles/examples/examples/#sec:hidkeyboarddemoExample
appears it would need to be 
https://bluekitchen-gmbh.com/btstack/#examples/examples/#sec:hidkeyboarddemoExample

Similar issues with the others, seems there may have been a slight rearrangement and these links werent fixed

**Comment by mringwal** [comment]
Hi there. On the develop branch (resp. its html manual), the links to source files as well as others have been fixed. Please let us know if you find other dead links

**Comment by daveHitchman** [comment]
super :)
