### ISSUE TITLE
Pairing with "Numeric Comparison" misses the passkey.

### ISSUE THREAD

**Issue by felixdoerre** [bluekitchen/btstack#462]
**Describe the bug**

Seemingly since ea9b67963c9 the passkey is not sent with the `SM_EVENT_NUMERIC_COMPARISON_REQUEST`-event, but the memory for the passkey is uninitialized. It seems that refactoring broke the logic and no test case caught it.

**To Reproduce**

1. Configure the stack to use secure connections, and io=display_yes_no
2. Initiate a pairing from a remote device that has e.g. display_keyboard
3. Receive the `SM_EVENT_NUMERIC_COMPARISON_REQUEST`
4. Extract the passkey from that event with `sm_event_numeric_comparison_request_get_passkey`
5. Notice that it not only does not match the key from the remote device, but also is out of range (e.g. `-731160572` in one run)

**Expected behavior**

In step "5" I would expect the passkey to be the same as shown on the remote device.

**Environment:  (please complete the following information):**
 - Micropython with btstack at: 1635e36d0
 - Bluetooth Controller CYW43 on Pico W
 - Remote device: Android

**Additional context**
I believe the refactoring broke the `NUMERIC_COMPARISON` case and `sm_trigger_user_response_passkey` should be extended to also be usable for `SM_EVENT_NUMERIC_COMPARISON_REQUEST`.

**Comment by mringwal** [comment]
Hi Felix. Thanks for the issue report and the bi-sect. You're totally right, when extracting the helper functions, the value for the Numeric Comparison event got lost. It's fixed on the develop branch. Could you confirm the fix?

**Comment by felixdoerre** [comment]
I've cherry-picked the fix locally on v1.5.4, tested a numeric comparison pairing and it resolves the issue. Thanks.
