### ISSUE TITLE
`btstack_is_null` defined but never used in certain configurations

### ISSUE THREAD

**Issue by dpgeorge** [bluekitchen/btstack#469]
When building v1.5.5 (and also master I think), the compiler will warn that the static `btstack_is_null` function is defined but never used, eg if `ENABLE_CLASSIC` and `ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION` are disabled.

**Comment by mringwal** [comment]
Thx. Fixed in 77955af6417aca198a9be05155384fb9bd2d510b on develop. I've cherry-picked it for master now.
