### ISSUE TITLE
SRC_BLE_GATT_SERVICE_FILES is wrong?

### ISSUE THREAD

**Issue by peterharperuk** [bluekitchen/btstack#478]
I don't use this myself but on master btstack/src/ble/gatt-service/Makefile.inc includes the following lines...

    mesh_provisioning_service_server.c \
    mesh_proxy_service_server.c \

These files have been moved from the ble folder to mesh?

**Comment by mringwal** [comment]
Hi @peterharperuk - could you double-check? in the current file https://github.com/bluekitchen/btstack/blob/master/src/ble/gatt-service/Makefile.inc I don't see any mesh_* files.

**Comment by peterharperuk** [comment]
Groan - you're right. I was looking at the wrong directory. Sorry to waste your time.

**Comment by mringwal** [comment]
no worries - it took only a quick look to confirm my suspicion that I had already sorted that.
