### ISSUE TITLE
how to use CC2564B to transmit I2S audio by itself (assisted A2DP – A3DP)?

### ISSUE THREAD

**Issue by yangn0** [bluekitchen/btstack#480]
Does btstack have such an implementation?
![image](https://github.com/bluekitchen/btstack/assets/35649701/81bf58de-ef9e-4fdd-bd29-a065216a67e9)
![image](https://github.com/bluekitchen/btstack/assets/35649701/a0875954-834e-412c-a84b-87523f3f666c)

**Comment by mringwal** [comment]
Hi there. BTstack supports the Assisted HFP if you define ENABLE_CC256X_ASSISTED_HFP in btstack_config.h
Support for mSBC is quite common, e.g. newer Infineon and Realtek Controllers have support for it as well.

BTstack does not support Assisted A2DP (A3DP). As mentioned in the Chipset document, most projects require BLE, so it's easier to decode SBC in software.
