### ISSUE TITLE
BTStack Port for ESP32 and HID Keyboard Mode

### ISSUE THREAD

**Issue by 6enno** [bluekitchen/btstack#49]
HID keyboard demo doesn't work out of the box (for me at least on the release branch).

Inspection of the example template file indicates that it is likely this issue still exists on master.

This is what the console looks like:

![image](https://user-images.githubusercontent.com/30337609/28510360-12f0c62c-709c-11e7-8e4c-d8093fd34084.png)

The reason seems to be the following in bt_stack_config.h:
`#define MAX_NR_L2CAP_SERVICES  2`

But hid_device_init() which is run from main in the demo seems to use more than 2 services. The fact that this is defined also means that malloc is not used even though it is available.

This is low priority and easily fixable but I thought I would bring it to light to save time for others.

**Comment by mringwal** [comment]
Hi @6enno Thanks for reporting. Interestingly, the MAX_NR_ defines have precedence over HAVE_MALLOC - which makes sense (it allows to limit some of the memory pools) - although I doubt that I did consider this in detail.

Anyway, I've removed the MAX_NR definitions, letting malloc do it's work.
