### ISSUE TITLE
Would be nice to open the "Discussions" tab on this repo. 

### ISSUE THREAD

**Issue by EdwinFairchild** [bluekitchen/btstack#490]
Not everything is an issue, sometimes   a simple question and a quick answer from the community is all that it amounts to. 
Discussions can be enabled from the Repo settings. Good thing is you can link code and specific lines etc.

**Comment by mringwal** [comment]
Hi Eddie. You are correct that thhe GitHub Issue Tracker isn't a good place to ask questions. For this, I'd prefer you post on our mailing list: https://groups.google.com/group/btstack-dev
