### ISSUE TITLE
ESP32 PANU in Arduino IDE

### ISSUE THREAD

**Issue by DansDesigns** [bluekitchen/btstack#494]
Hello, First i must say that i am amazed at the work that has been put into this, Kudos!

I would like to ask if it is possible to use the panu_demo.c example within the Arduino IDE for the ESP32?
If so, how would one go about incorporating this as a library?

Thank you for your help!

**Comment by mringwal** [comment]
Hi Dan, thanks for your kind words. The panu_demo only works on Linux and maybe on macOS as it assumes that a native TCP/IP stack exists and that it's possible to implement a virtual network card.
Our pan_lwip_http_server.c, which also includes a DHCP Server, would be a better example.

So far, I've only used BTstack with the ESP-IDF framework and haven't tried the Arduino IDE. You can follow the readme in the port/esp32 folder of BTstack to run the pan_lwip_http_server.c directly.
