### ISSUE TITLE
btstack not connecting in ios

### ISSUE THREAD

**Issue by drunkscientist** [bluekitchen/btstack#5]
no response https://code.google.com/p/btstack/issues/detail?id=454&start=100#makechanges so i thought id try it here, not sure where else to post/ask, https://dl.dropboxusercontent.com/u/9034873/hci_dump.pklg is the dump file, had someone else with the same problem as of this morning, so...

**Comment by mringwal** [comment]
I've answered on the old issue tracker. This one isn't for iOS apps etc.
