### ISSUE TITLE
btstack multiple connections, ESP32

### ISSUE THREAD

**Issue by my-abousamra** [bluekitchen/btstack#50]
Hi,

I wrote a simple application based on 2 btstack provided examples first is spp_streamer_client to connect to other BT devices and the second is spp_counter to accept connections from outside. It works well but every one alone when I establish a connection I can't receive connections and vice versa. Is there an example for such case or clear steps of how to do that?

Regards

**Comment by mringwal** [comment]
If you look at the console output, it should show a error allocating memory for the management structures. On smaller targets, a fixed number of services is used. For ESP32, with enough RAM, I've switched to use malloc. It's fixed/changed on the develop branch, see https://github.com/bluekitchen/btstack/commit/2c204492a050996e834496ea45f53670dffcc6f7
