### ISSUE TITLE
Is there an example for OTA?

### ISSUE THREAD

**Issue by xihua13104** [bluekitchen/btstack#513]
Is there an example for OTA over ble or classic?

**Comment by mringwal** [comment]
Not in the BTstack repository.

Feel free to ask on the mailing list as other users might have one.

In general, you need to get the current version and if there's a mismatch send a new firmware. However, there are many details (A/B update or delta updates, push/pull, how to update the flash itself, what bootloader to use/trust, ...) that will be project specific. esp-idf provides a most of this, so you'd only need to check the version and send the new firmware.
