### ISSUE TITLE
Whitelist add/remove sync problem 

### ISSUE THREAD

**Issue by amorniroli** [bluekitchen/btstack#520]
**Describe the bug**

In some circumstances, devices are not added to whitelist because they are recognized as "ON_CONTROLLER", even if they have been physically removed from the controller.

E.g.

    gap_whitelist_add (BD_ADDR_TYPE_LE_PUBLIC, address0);
    gap_whitelist_add (BD_ADDR_TYPE_LE_PUBLIC, address1);

    //wait some time
    
    gap_whitelist_clear ();
    gap_whitelist_add (BD_ADDR_TYPE_LE_PUBLIC, address0);
    gap_whitelist_add (BD_ADDR_TYPE_LE_PUBLIC, address1);
 
**To Reproduce**

1. Run example [whitelist_issue.txt](https://github.com/bluekitchen/btstack/files/12310565/whitelist_issue.txt) (rename to .c)

**Expected behavior**

I would expect that both addresses will be in the whitelist of the controller.

**HCI Packet Logs (wireshark)**
rename to .pklg

[whitelist_fail.txt](https://github.com/bluekitchen/btstack/files/12310557/whitelist_fail.txt)
[whitelist_workaround.txt](https://github.com/bluekitchen/btstack/files/12310558/whitelist_workaround.txt) (described at the end of the issue)

**Environment:  (please complete the following information):**
 - v1.5.6.2-extra

**Additional context**

I think the problem is that calling gap_whitelist_clear, will trigger hci_run, and if HCI command is ready to be sent, the first address is removed physically from the controller.

hci.c, line 6358:

```
entry->state &= ~LE_WHITELIST_REMOVE_FROM_CONTROLLER;
hci_send_cmd(&hci_le_remove_device_from_white_list, entry->address_type, entry->address);
```
				
At this point, entry->state has still LE_WHITELIST_ON_CONTROLLER bit active. Calling gap_whitelist_add after gap_whitelist_clear, will issue return ERROR_CODE_COMMAND_DISALLOWED (hci.c line 8664), because address is still recognized as LE_WHITELIST_ON_CONTROLLER, even if it has ben removed from the controller.

Right now, as workaround, I'm just clearing bit LE_WHITELIST_ON_CONTROLLER when calling HCI cmd hci_le_remove_device_from_white_list (see next snippet code)

```
if (entry->state & LE_WHITELIST_REMOVE_FROM_CONTROLLER){
    entry->state &= ~LE_WHITELIST_REMOVE_FROM_CONTROLLER;
    entry->state &= ~LE_WHITELIST_ON_CONTROLLER;
    hci_send_cmd(&hci_le_remove_device_from_white_list, entry->address_type, entry->address);
    btstack_linked_list_remove(&hci_stack->le_whitelist, (btstack_linked_item_t *) entry);
    btstack_memory_whitelist_entry_free(entry);
    return true;
}
```

Besides, I've noticed that this snippet of code (hci.c line 6369 of v1.5.6.2-extra, but should be the same also in v1.5.6.3) was never called.

```
if ((entry->state & LE_WHITELIST_ON_CONTROLLER) == 0){
    btstack_linked_list_remove(&hci_stack->le_whitelist, (btstack_linked_item_t *) entry);
    btstack_memory_whitelist_entry_free(entry);
}
```

**Comment by mringwal** [comment]
Hi Alessandro. Could you try with latest version on master or develop? I think we've fixed this recently.

**Comment by amorniroli** [comment]
> Hi Alessandro. Could you try with latest version on master or develop? I think we've fixed this recently.

Hi @mringwal , I confirm that on develop branch the bug is resolved. Sorry for bothering you: I always forget to check 'develop' branch prior to open an issue. 

Thank you very much!

**Comment by mringwal** [comment]
No problem. I'm sorry you had to run into that one - and it's not even on the master branch yet.
