### ISSUE TITLE
Stream data with Bluetooth LE

### ISSUE THREAD

**Issue by gianalbertochini** [bluekitchen/btstack#530]
I'm trying to write an application for my thesis. I don't know if this is the best place to write my question

I've chosen the Raspberry pi Pico W platform to implement that but I'm unable to achieve what I want 

I would like be able to transmit around 20kB of data from a Raspberry Pi Pico W called Client to one Raspberry Pi pico W called Server and later Server send back (after some processing) data again to the client.

My goal si to send 20kB of data fron the Client to the Server and from the Server to the client using BLE.

My question are
- can i do that? I think that I  can because I've bought a chinese labeler that transmit the data (even images) using BLE. 
- there is an example that i can use or that i can modify in order to get what i want?
- how i can do?

I've still tried an adapted to the Raspberry Pi Pico W allmost all examples found in BTStack's github but I am unable to figure out why some does not work

I was able to make it work the standalone example found in the Raspberry Pi Pico W repository
I was able to send a GAP message in broadcast from a Broascaster and read it by an Observer

Thanks for your help in advance

**Comment by mringwal** [comment]
**Discussion and Community Support:** [BTstack Google Group](https://groups.google.com/group/btstack-dev)
