### ISSUE TITLE
Please release new version to fix hid_device functionality

### ISSUE THREAD

**Issue by shuffle2** [bluekitchen/btstack#533]
Please release a new version, such that projects like pico-sdk can update their version of btstack to include fixes such as those which were made to `hid_device.c` in the last few months. I've implemented a hid device on raspberry pi pico W recently, and had to spend a couple days debugging why it wasn't working - only to discover a fix for the problem was sitting in the btstack develop branch. 

The problem was that the hid device's `protocol_mode` was defaulting to `HID_PROTOCOL_MODE_BOOT` and never being set to `HID_PROTOCOL_MODE_REPORT`, since `hid_device_provide_instance_for_bd_addr` never got called. Now that the default is REPORT mode, it works fine.

6c8af51cd8ad0a0d53fc3934daf633474c3bec06 fixed it.

Some of the other recent changes look important, too.

**Comment by mringwal** [comment]
Sorry for the unnecessary debugging time. We didn't have a tag/release in a while and the official release of the HFP v1.9 spec (and our final implementation of that) is a good trigger for a new release. We still have a few tests to pass there and some other preparations to do.

**Comment by mringwal** [comment]
Interesting. What's the use case for a HID device being connected to two HID hosts? I can imagine being active only to one and switch between them, but not really sending to both of them in parallel.

When we implement a new profile, we usually implement it for a single connection if that's useful in most cases, but provide something like the hid_device_t struct to allow for later extension for multiple connections.

As for you issue: if possible, post an HCI packet log and add log_info calls to make your app logic more visible. The logic to call hid_device_request_can_send_now_event and send a packet upon HID_SUBEVENT_CAN_SEND_NOW is correct. You could test/debug this with the original code to rule out a detail with your multiple connection implementation.

**Comment by mringwal** [comment]
Thanks for the explanation. After sending BD ADDR and link key over USB and an initial connection from the game controller to the PS5 (to learn the game controller BD ADDR), they already have a fully authenticated (aka mitm-protected) connection without any user interaction. I would have just read the BD ADDR via USB as well. No idea what other potential problem this addresses.

Thanks for the 'hacky patch'. It's rather complete - and the TODOs are already in place!

**Comment by mringwal** [comment]
Hi there. I've reworked hid_device.c to support multiple connections now. Could you try it on develop-hid-device branch and let me know if ti works for you? You'd need to set MAX_NR_HID_DEVICE_CONNECTIONS to 2 in btstack_config.h
