### ISSUE TITLE
Very strange code

### ISSUE THREAD

**Issue by VBKesha** [bluekitchen/btstack#538]
In file hci.h

```
       if ((connection->bonding_flags & BONDING_SEND_AUTHENTICATE_REQUEST) && ((connection->bonding_flags & BONDING_RECEIVED_REMOTE_FEATURES) != 0)){
            connection->bonding_flags &= ~BONDING_SEND_AUTHENTICATE_REQUEST;
            connection->bonding_flags |= BONDING_SENT_AUTHENTICATE_REQUEST;
            hci_send_cmd(&hci_authentication_requested, connection->con_handle);
            return true;
        }

```

Why we clear flag BONDING_SEND_AUTHENTICATE_REQUEST but in next line we set his back again. Its normal or misprint?

**Comment by mringwal** [comment]
Hi. This implements actions that have to be performed and we also track which we already executed. If BONDING_SEND_AUTHENTICATE_REQUEST is set, we clear it and set the different flag BONDING_SENT_AUTHENTICATE_REQUEST ("send" -> "sent") to track that we did.
