### ISSUE TITLE
Receiving HID output reports from host

### ISSUE THREAD

**Issue by fullmetalfelix** [bluekitchen/btstack#547]
I have managed to setup a PiZero as HID (classic) bluetooth joystick and now would like to add force-feedback. I have read this is possible with output reports that are sent by the host. However, I cannot find a way to have my program receive them.
Is there a specific event to look for in the packet handler?
Or a specific callback to register like hid_device_register_report_data_callback? Is there any example of HID device using this?

Thanks for helping.

**Comment by mringwal** [comment]
You should get output reports via the callback set by hid_device_register_set_report_callback().

Please post user questions on the BTstack mailing list. This is not a stack issue.
