### ISSUE TITLE
Compile error in ble/sm.c:1321:104 when LE_CENTRAL is not enabled

### ISSUE THREAD

**Issue by fominykhandrei** [bluekitchen/btstack#554]
btstack/src/ble/sm.c:1321:104: error: use of undeclared identifier 'authenticated'; did you mean 'gap_authenticated'?
                    le_device_db_encryption_get(sm_connection->sm_le_db_index, NULL, NULL, ltk, NULL, &authenticated, NULL, NULL);
                                                                                                       ^~~~~~~~~~~~~
                                                                                                       gap_authenticated

"authenticated" is declared under #ifdef ENABLE_LE_CENTRAL

**Comment by mringwal** [comment]
Thanks for reporting. It's fixed in 45d80b0 on develop branch
