### ISSUE TITLE
Compile with  ENABLE_GATT_OVER_CLASSIC flag in version 1.6 does not work for me

### ISSUE THREAD

**Issue by tamv12** [bluekitchen/btstack#562]
HI, 
I added this flag to btstack_config.h.
compilation works in version 1.53 but not in 1.6
thanks

**Comment by mringwal** [comment]
Hi there. Could you also post the compiler error as well as your btstack_config.h file? Adding ENABLE_GATT_OVER_CLASSIC compiles with master/v1.6 as well as develop branch in port/libusb.

**Comment by mringwal** [comment]
Closing for now. Please re-open if this can be reproduced on the develop branch in one of the existing ports
