### ISSUE TITLE
Pi Pico W BLE Extended Advertising Not Working(?)

### ISSUE THREAD

**Issue by dmalnati** [bluekitchen/btstack#563]
**Describe the bug**

Using the RPi Pico W and the pico-sdk v1.5.1 (latest).

Using the btstacks GAP API ([link](https://bluekitchen-gmbh.com/btstack/#appendix/gap/)) on the Pico.
I am using the Android version of the nRF Connect app ([link](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_US&gl=US)) to monitor BLE Advertisements.

I am able to use the classic Advertisement API to successfully create advertisements seen from the app, consisting of the sequence of:
* `gap_advertisements_set_params()`
* `gap_advertisements_set_data()`
* `gap_advertisements_enable()`

However, the bug, is that I do not appear to be able to detect errors in using, or the effect of seeing advertisements, using the the Extended Advertisement API.

That is, I use:
* `gap_extended_advertising_setup()`
* `gap_extended_advertising_set_adv_data()`
* `gap_extended_advertising_start()`

These functions return success codes, their parameters are all statics, and yet no visible advertisements seen.

The API ([link](https://bluekitchen-gmbh.com/btstack/#appendix/gap/)) for GAP is just a list of function prototypes, no specific guidance given on sequence, how to fill out structure params, etc.

However, I did find the `le_audio_broadcast_source.c` ([link](https://github.com/bluekitchen/btstack/blob/72ef1732c954d938091467961e41f4aa9b976b34/test/le_audio/le_audio_unicast_source.c)) implementation within the pico-sdk/lib/btstack/test/le_audio directory, and that implementation exercises this API.

I have copied the usage of the API by directly copy/pasting the parameters as statics, and the function call sequence, into my application, with no successful visible advertisements and no errors.  I have tried this with both the subset of only `gap_extended_advertising_*` calls, as well as the implementation's simultaneous usage of the `gap_periodic_advertising_*` calls as well.

Additionally, I have two Android devices, and using the nRF Connect app on both, I can cause one to advertise BLE Extended Advertisements, and the other successfully detects them.  Neither device successfully detects the Pico emitting Extended Advertisements.

Additionally, I am using the nRF Bluetooth LE Sniffer ([link](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_sniffer_ble%2FUG%2Fsniffer_ble%2Finspecting_data.html)) device, which allows Wireshark to sniff Bluetooth packets.  Using this device, I am not able to detect Pico-originated Extended Advertising packets, but I am able to detect Android-originated Extended Advertising packets (via nRF Connect app).

Because of the above, I think the btstacks library for the sdk is not working as expected for Pico W.

**To Reproduce**

Do the above.

**Expected behavior**

I expected to see advertisements or an error return code.

**HCI Packet Logs**

Sorry I wasn't able to get this to compile, thoughts on what to change?
```
C:/Users/dougl/git/pico/lib/BLE/Ble.cpp:218:19: error: 'hci_dump_embedded_stdout_get_instance' was not declared in this scope
  218 |     hci_dump_init(hci_dump_embedded_stdout_get_instance());
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[93/99] Building CXX object LIB_PICO/CMakeFiles/LibPico.dir/BLE/BleGatt.cpp.obj
ninja: build stopped: subcommand failed.
```

**Environment:  (please complete the following information):**

 - Current BTstack branch: sdk-pico v1.5.1's submodule version ([link](https://github.com/bluekitchen/btstack/tree/72ef1732c954d938091467961e41f4aa9b976b34))
 - Bluetooth Controller Pico W cyw43
 - Remote device: Android running nRF Connect

**Additional context**

btstack_config.h:
```
#ifndef _PICO_BTSTACK_BTSTACK_CONFIG_H
#define _PICO_BTSTACK_BTSTACK_CONFIG_H

// started from https://github.com/raspberrypi/pico-examples/blob/master/pico_w/bt/config/btstack_config.h

// BTstack features that can be enabled
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_LE_ENHANCED_CONNECTION_COMPLETE_EVENT
#define ENABLE_LE_EXTENDED_ADVERTISING
#define ENABLE_LE_PERIODIC_ADVERTISING
#define ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_CONTROLLER_WARM_BOOT
#define ENABLE_ATT_DELAYED_RESPONSE




#define ENABLE_LOG_INFO



#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
#define ENABLE_PRINTF_HEXDUMP
#define ENABLE_SCO_OVER_HCI

// BTstack configuration. buffers, sizes, ...
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_PAYLOAD_SIZE (1691 + 4)
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
#define MAX_NR_AVDTP_CONNECTIONS 1
#define MAX_NR_AVDTP_STREAM_ENDPOINTS 1
#define MAX_NR_AVRCP_CONNECTIONS 2
#define MAX_NR_BNEP_CHANNELS 1
#define MAX_NR_BNEP_SERVICES 1
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES  2
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 2
#define MAX_NR_HID_HOST_CONNECTIONS 1
#define MAX_NR_HIDS_CLIENTS 1
#define MAX_NR_HFP_CONNECTIONS 1
#define MAX_NR_L2CAP_CHANNELS  4
#define MAX_NR_L2CAP_SERVICES  3
#define MAX_NR_RFCOMM_CHANNELS 1
#define MAX_NR_RFCOMM_MULTIPLEXERS 1
#define MAX_NR_RFCOMM_SERVICES 1
#define MAX_NR_SERVICE_RECORD_ITEMS 4
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_WHITELIST_ENTRIES 16
#define MAX_NR_LE_DEVICE_DB_ENTRIES 16

// Limit number of ACL/SCO Buffer to use by stack to avoid cyw43 shared bus overrun
#define MAX_NR_CONTROLLER_ACL_BUFFERS 3
#define MAX_NR_CONTROLLER_SCO_PACKETS 3

// Enable and configure HCI Controller to Host Flow Control to avoid cyw43 shared bus overrun
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define HCI_HOST_ACL_PACKET_LEN 1024
#define HCI_HOST_ACL_PACKET_NUM 3
#define HCI_HOST_SCO_PACKET_LEN 120
#define HCI_HOST_SCO_PACKET_NUM 3

// Link Key DB and LE Device DB using TLV on top of Flash Sector interface
#define NVM_NUM_DEVICE_DB_ENTRIES 16
#define NVM_NUM_LINK_KEYS 16

// We don't give btstack a malloc, so use a fixed-size ATT DB.
#define MAX_ATT_DB_SIZE 512

// BTstack HAL configuration
#define HAVE_EMBEDDED_TIME_MS

// map btstack_assert onto Pico SDK assert()
#define HAVE_ASSERT

// Some USB dongles take longer to respond to HCI reset (e.g. BCM20702A).
#define HCI_RESET_RESEND_TIMEOUT_MS 1000

#define ENABLE_SOFTWARE_AES128
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS

#define HAVE_BTSTACK_STDIN

// To get the audio demos working even with HCI dump at 115200, this truncates long ACL packets
//#define HCI_DUMP_STDOUT_MAX_SIZE_ACL 100

#ifdef ENABLE_CLASSIC
#define ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE
#endif

#endif // _PICO_BTSTACK_BTSTACK_CONFIG_H
```

CMakeLists.txt excerpts
```
set(PICO_BOARD pico_w)

...

set(BTSTACK_ROOT ${PICO_SDK_PATH}/lib/btstack)
target_include_directories(${PROJECT_NAME} PRIVATE
    ${BTSTACK_ROOT}/src
)

target_link_libraries(${PROJECT_NAME}
    pico_stdlib
    pico_rand
    FreeRTOS-Kernel
    FreeRTOS-Kernel-Heap3
    tinyusb_device
    tinyusb_host
    pico_cyw43_arch_none
    pico_btstack_cyw43
    pico_btstack_ble
    LibPico
)
```

**Comment by mringwal** [comment]
Hi. Thanks for the detailed report. To see what's going wrong, we need the HCI trace. There also have been fixes to Extended Advertising which basically wasn't used before development for LE Audio started.

Please switch to branch develop of btstack, add missing .c files to pico CMakeFile, enable hci trace, and try again.
hci_dump_embedded_stdout_get_instance() is from btstack/platform/embedded/hci_dump_embedded_stdout.h
The C file is btstack/platform/embedded/hci_dump_embedded_stdout.c

---

hm.. on seconds thoughts: I'm not sure if the CYW43439 supports Extended Advertising. In fact, it doesn't look like it's supported.

 The latest Bluetooth SIG listing 222970 from 2023-09-14 is this:
https://launchstudio.bluetooth.com/ListingDetails/194078 (public)

It's ICS are here:
https://launchstudio.bluetooth.com/ICSDetails/222970 (requires free registration)

In the LL (Low Energy Link Layer), Extended Advertising is not selected.

**Comment by peterharperuk** [comment]
The Pico folks are unlikely to know and would have to ask the wifi chipset vendor.

**Comment by mringwal** [comment]
Thanks for the HCI log. During startup, BTstack checks which commands and features are supported. For Extended Advertising, it checks if "HCI LE Extended Advertising Enable" is supported, which would be internal command id 0x0e with octet 36, bit 6, which is not set. Together with the Bluetooth SIG listing and the datasheet, we can conclude that the 43439 does not support extended advertising. Sorry.

As for other broadcast options: if you want to stick to the Pico W, you can rotate advertisements, e.g. add a "virtual advertisement offset" field and split your data into multiple chunks. Or, you can use Wifi - I have no experience with that. BTstack allows to send custom HCI Commands, but I'm not aware of any vendor-specific commands for broadcast. Ah.. you could also use the classic inquiry mechanism, which allows to send up to 250 byte Extended Inquiry Responses, see gap_set_extended_inquiry_response.

**Comment by mringwal** [comment]
I'm not 100% sure, but no Extended Advertising => no Periodic Advertisement in general.
With extended advertising, you could request to only send a few advertisements and then get a 'advertising set terminated' event. 

With regular advertising, there's no clear support for ti, but... if the Controller isn't doing anything right now, it's fair to assume that it starts advertising right away, so, I'd suggest to use a timer and set it to e.g. 3 ms, update the advertising data after that and then check/test if that works. if not, increase the timer :)

For general discussion, feel free to join the BTstack Google Group / Mailing List.
