### ISSUE TITLE
How to include HID descriptors from usb keyboard in btstack

### ISSUE THREAD

**Issue by emanuellopes** [bluekitchen/btstack#569]
Hi,
In my project I'm trying to modify my keyboard to work with ble.

At this moment I already extracted the original keyboard HID descriptors using a cli tool https://github.com/todbot/mac-hid-dump.

I was able to extract 3 types of reports.

- the first file I have Keyboard, Sys Control, Consumer control and two vendors( I don't know what this vendors does).

- The second file Is a keyboard report but more extensive, but this report doesn't have any reportID associated.

- the third file I have another vendor report.

So, At this moment using the report from btstack hid_keyboard example, I was able to write everything in from keyboard, so after that, I have appended the consumer report from my keyboard and I was able to use media keys.

In my code, I was converted the report id != 3 to 5 report number 3 is consumer and 5 is the keyboard.

I tried add all my reports into HID_descriptor but I receive a kernel panic.

- Another issue, it's related with capsLock LED, I have fixed this on tinyusb side with this code
```c
leds ^= KEYBOARD_LED_CAPSLOCK; //  = 2
      tuh_hid_set_report(dev_addr, instance, 0, HID_REPORT_TYPE_OUTPUT, &leds, sizeof(leds));
```
I'm not sure if this can be fixed on Btstack side.

[kb_report_v1.txt](https://github.com/bluekitchen/btstack/files/14516394/kb_report_v1.txt)
[kb_report_v2.txt](https://github.com/bluekitchen/btstack/files/14516395/kb_report_v2.txt)
[kb_report_v3.txt](https://github.com/bluekitchen/btstack/files/14516396/kb_report_v3.txt)

this is my [repository code](https://github.com/emanuellopes/picow-keyboard-ble-classic/blob/fix-media-keys-with-fn/src/btstack/header/hid_descriptor.h)

I already read a lot but I'm not sure why I can't use the same HID descriptor from keyboard inside btatck.

I used a app [device monitoring studio](https://hhdsoftwaredocs.online/dms/introduction/overview.html) and notice, the default keyboard keys doesn't have any report ID associated.

The report ID is not mandatory?

Sorry for the questions, I'm hope your answers can help more people.

Thank you

**Comment by mringwal** [comment]
Hi Emanuel. This is not an issue of BTstack. Feel free to post on the mailing list, and I might be answer some of your questions.
