### ISSUE TITLE
Is SSP classic support planned?

### ISSUE THREAD

**Issue by asuivelentine** [bluekitchen/btstack#57]

**Comment by mringwal** [comment]
Secure Simple Pairing (SSP) for Classic is supported and enabled by default. Why do you ask? 

Could you post general questions on the BTstack mailing list? Others might be able to answer as well there.

**Comment by aknik** [comment]
Is Secure Simple Pairing (SSP) for Classic supported and enabled by default for ESP32 ?
I don't know how to use it.

**Comment by mringwal** [comment]
It is. You can configure it using gap_ssp_* functions in src/gap.h like gap_ssp_set_io_capability and gap_ssp_set_authentication_requirement Constants for both are SSP_ in src/bluetooth.h.
