### ISSUE TITLE
Hog multiples hid descriptor 

### ISSUE THREAD

**Issue by emanuellopes** [bluekitchen/btstack#576]
Hi, it's me again. 

Sorry for sending a lot of comments here, but I have some doubts, and I know you have the right answer for me.

In classic examples, we can have multiple hid descriptors, and in report data,  we should send the report ID to identify the device, for example, a keyboard and a consumer control.

The examples show how to use report ID and works fine.

Now I'm exploring BLE examples because the battery service that I will need.

But at this moment I'm facing the following issue.

1. How BLE deal with multiples reports?
2. There is a mechanism or other function to with that?

Off course, I tried the same approach as we have in classic version but without success.

Thank you again

**Comment by mringwal** [comment]
Please ask on the mailing list.

In HID over GATT, each report uses a separate Characteristic. We did only implement support for a single report per type, but later added hids_device_send_input_report_for_id that allows to send different input reports.
