### ISSUE TITLE
Wrong address_type and address in some examples

### ISSUE THREAD

**Issue by xiaobye-ctf** [bluekitchen/btstack#579]
https://github.com/bluekitchen/btstack/blob/de13ba803acdb54c41ebfbca4e795757f719a2dd/example/gatt_battery_query.c#L198C1-L212C19
https://github.com/bluekitchen/btstack/blob/de13ba803acdb54c41ebfbca4e795757f719a2dd/example/gatt_device_information_query.c#L196C1-L210C19
In these examples, `report.address_type` and `report.address` has not been assigned a value, which could lead to unknown behavior in `gap_connect`.

**Comment by mringwal** [comment]
fixed in 041b66c. Thanks!
