### ISSUE TITLE
btstack_stdin interface!

### ISSUE THREAD

**Issue by WallGeorg** [bluekitchen/btstack#58]
Hi.
I received your email as follow.
![2](https://user-images.githubusercontent.com/30696128/29010110-4220da62-7b29-11e7-8527-2bf8d45e1cc4.png)
I want to know btstack_stdin interface.
Also I see as follow.
![3](https://user-images.githubusercontent.com/30696128/29010158-a01be792-7b29-11e7-8375-d83926182974.png)
Could you explain me about this.
Best regards.

**Comment by mringwal** [comment]
see http://bluekitchen-gmbh.com/cross-platform-console-input/
Also, I've implemented the stdin interface yesterday.
