### ISSUE TITLE
What‘s W2 or W4 prefix mean?

### ISSUE THREAD

**Issue by lgnativs** [bluekitchen/btstack#588]
There are many macro defines prefixes starting with W2 or W4 in the project. I am curious what they mean?

**Comment by mringwal** [comment]
Hi there. As everything is asynchronous in the stack, many state machines are waiting for something to happen and we use 'W4' = 'wait for' to indicate that. When the event happens, it becomes ready but might not be able to react/send something. Here, we often use 'W2' = 'wait to'.

Feel free to ask on the mailing list.
