### ISSUE TITLE
Remove force baudrate to 3000000 for broadcom chipsets

### ISSUE THREAD

**Issue by amorniroli** [bluekitchen/btstack#595]
**Is your feature request related to a problem? Please describe.**
Not really a problem.

**Describe the solution you'd like**
There is a limitation in hci.c which is forcing baudrate to 3000000 mbps for broadcom chipsets. In my case (CYW20706), I have no problems with DMA and 4000000 baudrate mbps.

![image](https://github.com/bluekitchen/btstack/assets/4875195/b9366d5c-b62c-4743-a0e4-8999cea12695)

I'd like to have this limitation put under a configuration define.

**Describe alternatives you've considered**
/

**Additional context**
/

Best regards,

Alessandro

**Comment by mringwal** [comment]
Hi Alessandro. That limitation is rather historic. I think some older chipsets fail to upload the PatchRAMat 4 mbps. Anyway, as none of the examples ports use 4 mbps by default and the main baud rate is set by the application/port, I've just removed the code (until someone shows up with a realistic use case for this). If it's needed in the future (for yet unknown reasons), we'll add a compile time flag that's needed to enable it.

Fix/Removed on develop branch
