### ISSUE TITLE
ESP32: Compilation errors after btstack update

### ISSUE THREAD

**Issue by my-abousamra** [bluekitchen/btstack#61]
Hi,

My application was working well until I updated btstack yesterday were it started to complain in compilation about missing defines

C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:86:2: error: #error "NVM_NUM_DEVICE_DB_ENTRIES not defined, please define in btstack_config.h"
 #error "NVM_NUM_DEVICE_DB_ENTRIES not defined, please define in btstack_config.h"
  ^
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:90:2: error: #error "NVM_NUM_DEVICE_DB_ENTRIES must not be 0, please update in btstack_config.h"
 #error "NVM_NUM_DEVICE_DB_ENTRIES must not be 0, please update in btstack_config.h"
  ^
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:93:27: error: 'NVM_NUM_DEVICE_DB_ENTRIES' undeclared here (not in a function)
 static uint8_t  entry_map[NVM_NUM_DEVICE_DB_ENTRIES];
                           ^
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:93:17: warning: 'entry_map' defined but not used [-Wunused-variable]
 static uint8_t  entry_map[NVM_NUM_DEVICE_DB_ENTRIES];
                 ^
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c: In function 'le_device_db_tlv_fetch_mapped':
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:148:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c: In function 'le_device_db_tlv_store_mapped':
C:/Users/pulse/workspace/spp_counter_8/components/Bt_Stack/../../../../../../esp/btstack/src/ble/le_device_db_tlv.c:156:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1.exe: some warnings being treated as errors
make[1]: *** [/c/esp/esp-idf-v2.1/make/component_wrapper.mk:211: ../../../../../../esp/btstack/src/ble/le_device_db_tlv.o] Error 1
make: *** [C:/esp/esp-idf-v2.1/make/project.mk:386: Bt_Stack-build] Error 2

**Comment by mringwal** [comment]
We have implemented storage for LE pairing information in Flash. The compiler error is quite accurate. Just add e.g. #define NVM_NUM_DEVICE_DB_ENTRIES 16 to your btstack_config.h file. If you recreate the examples, they will compile.
