### ISSUE TITLE
simultaneous use of multiple profiles

### ISSUE THREAD

**Issue by DesignerAnGav** [bluekitchen/btstack#610]
Hello everyone. Is it possible to use two bluetooth profiles in one application using your library? for example hfp_ag and spp? I managed to do this using esp32, with the correct configuration of sdkconfig.

**Comment by mringwal** [comment]
Hi Anton. Yes, it is. Basically, you'll need to merge the init parts and the packet handlers. 

https://bluekitchen-gmbh.com/btstack/#examples/examples/#dual-mode-spp-and-le-counter example shows and explains how Classic SPP and LE GATT can be combined in a single app. The same is possible by adding an SPP/RFCOMM channel to the hfp_ag_demo.

Please ask general questions on the [mailing list](https://groups.google.com/group/btstack-dev)
