### ISSUE TITLE
SUPPORTED_HCI_COMMAND_LE_SET_EXTENDED_ADVERTISING_ENABLE is defined incorrectly

### ISSUE THREAD

**Issue by thewierdnut** [bluekitchen/btstack#624]
**Describe the bug**

SUPPORTED_HCI_COMMAND_LE_SET_EXTENDED_ADVERTISING_ENABLE defined as byte 36, bit 6, when it is supposed to be bit 5. 

(I'm referencing the table in the Core bluetooth 5.2 spec, Vol 4, Part E, 6.27)

**To Reproduce**

The chipset I'm working with doesn't implement either bit, so it doesn't really matter to me... just thought you would want to know. 

**Expected behavior**

Should be bit 5, not bit 6.

**HCI Packet Logs**

None

**Environment:  (please complete the following information):**
 - Current BTstack branch: develop

**Additional context**
I haven't tried using this yet, just rooting through the code, comparing it to the spec.

**Comment by mringwal** [comment]
Thanks for spotting this. It's fixed on develop branch now.
