### ISSUE TITLE
Typo in gatt_client.c

### ISSUE THREAD

**Issue by Squidniiii** [bluekitchen/btstack#627]
**Describe the bug**

Apparent typo in src/ble/gatt_client.c on line 2083.

Currently:

case P_W4_SEND_SINGED_WRITE_DONE:

Should be:

case P_W4_SEND_SIGNED_WRITE_DONE:

**To Reproduce**

Causes compile error when that section of code is compiled.

**Expected behavior**

Should compile, line needs to be changed to:

case P_W4_SEND_SIGNED_WRITE_DONE:

**Environment:  **
 - Current BTstack branch:master
 - Bluetooth Controller: N/A
 - Remote device: N/A

**Comment by mringwal** [comment]
Thanks for reporting. We fixed this one on a private branch a while ago but failed to merge it onto develop (and master).
It's fixed on develop now.
