### ISSUE TITLE
Add support for others PBAP application parameters

### ISSUE THREAD

**Issue by amorniroli** [bluekitchen/btstack#628]
**Is your feature request related to a problem? Please describe.**
Not real a problem. Our application requires to perform operation on PBAP based also on:

- order
- search value
- search property

**Describe the solution you'd like**
Add support for these application parameters (as done for max list count)

**Describe alternatives you've considered**
/

**Additional context**
Patch attached (30cf4543ab40181b6af587c081176b6787f3be77  as starting point)

[patch.txt](https://github.com/user-attachments/files/17042580/patch.txt)

**Comment by mringwal** [comment]
Thanks for the suggestions and the patch. It's added in 8981e44 on develop branch.
