### ISSUE TITLE
hci_dump.c: variable undeclared

### ISSUE THREAD

**Issue by jonas-wago** [bluekitchen/btstack#636]
When having `ENABLE_LOG_BTSTACK_EVENTS` defined, the compilation terminates for me in https://github.com/bluekitchen/btstack/blob/2b49e57bd1fae85ac32ac1f41cdb7c794de335f6/src/hci_dump.c#L121
because `size` is undeclared.

I think `len` is the correct variable instead of `size`?
https://github.com/bluekitchen/btstack/blob/2b49e57bd1fae85ac32ac1f41cdb7c794de335f6/src/hci_dump.c#L119

**Comment by mringwal** [comment]
Yupp. Already merged the fix. 

The ENABLE_LOG_BTSTACK_EVENTS flag will cause BTstack to also write (a subset) of the internal HCI-like events to the packet log. They will show up as "Undefined" or "Reserved" in tools like Wireshark - which is why we've disabled this by default.
