### ISSUE TITLE
BCM20733 Problem!!!

### ISSUE THREAD

**Issue by WallGeorg** [bluekitchen/btstack#66]
Hi.
I want to know BCM20733 Bluetooth firmware develop.
I knew that BCM20733 firmware can be developed with WICED.
Would I develop BCM20733 firmware with you btstack?
I hope your help.
Could you help me?
Best regards.

**Comment by mringwal** [comment]
Please post general/support questions on the BTstack mailing list.

What dev kit do you use?
In WICED Studio 4.1, I don't see a folder for 20733.

We tested BTstack with the 43xxx-Wi-Fi Controllers used in RedBear Duo and others.

**Comment by WallGeorg** [comment]
Hi.
I have BT3GMD-B60P module.
![4_eea0108973628e44e70af6f9f22246fd](https://user-images.githubusercontent.com/30696128/29542687-145ca2b4-86dc-11e7-9604-be6f0f77288c.jpg)
I don't know SDK and download device and connect method...
I hope your help.
Best regards.
