### ISSUE TITLE
Chipset: BCM20733 Support?

### ISSUE THREAD

**Issue by WallGeorg** [bluekitchen/btstack#67]
Hi.
I have BT3GMD-B60P module.
![4_eea0108973628e44e70af6f9f22246fd](https://user-images.githubusercontent.com/30696128/29542732-5409efd4-86dc-11e7-9339-e5d85a504934.jpg)

I don't know SDK and download device and connect method...
I hope your help.
Best regards.

**Comment by mringwal** [comment]
Hi. We don't know either :)

In the current WICED Studio 5.1 there is only support for 43xxx-Wifi and 20706-A2. Please check with Broadcom/Cypress how to work with this module and if allows to use a third-party Bluetooth stack.

**Comment by WallGeorg** [comment]
Hi.
I heard that SDK2.2.3 is supported for BCM20733.
But I don't confirm it.
If you know this method, let's me know.
Could you addition this SDK to your project.
I don't know this method.
Please, please Help me.
Best regards.

**Comment by mringwal** [comment]
The oldest WICED SDK on Cypress' site is for 3.x. There is a single question about the BCM20733 in the Cypress forum. Looks like this chip is not publicly supported by Cypress.

**Comment by WallGeorg** [comment]
Hi.
https://community.cypress.com/community/wiced-smart/wiced-smart-documentation
Pls, See this URL.
I hope your help.
Best regards.

**Comment by mringwal** [comment]
The WICED Smart SDK only covers BLE only chipsets. It does not cover the 20733, which seems to be an ARM Cortex M3 with a dual-mode Bluetooth radio.

Thanks for the nice overview pdf. Please contact Cypress Sales to get access to their HID Development Kit. It cannot be used with a different stack easily.

**Comment by WallGeorg** [comment]
Hi.
I know BCM20733 hasn't BLE, but there is ARM Cortex-M3.
Please See attached PNG.
![screen](https://user-images.githubusercontent.com/30696128/29568925-2de4cd8a-8752-11e7-8bba-e9e02b0f82b5.png)
Could you explain?
I am a beginner.
I want to know develop method.
Best regards.

**Comment by mringwal** [comment]
I'm sure it's technically possible. It looks like it's an SoC, which means the Bluetooth Controller is implemented in software and there might be an API to send/receive HCI packets. This would require reverse engineering existing BCM20733 firmware. 

As a beginner, I can only recommend to start with one of the already supported MCU + chipset combinations. And/or run BTstack on Linux with an USB Bluetooth dongle.

**Comment by WallGeorg** [comment]
Hi. 
What is means?
![screen](https://user-images.githubusercontent.com/30696128/29569403-b26c3ea2-8753-11e7-8ef8-1f154b7b5a67.png)
I don't know develop method.
Also I don't understand "It looks like it's an SoC, which means the Bluetooth Controller is implemented in software and there might be an API to send/receive HCI packets. This would require reverse engineering existing BCM20733 firmware.

As a beginner, I can only recommend to start with one of the already supported MCU + chipset combinations. And/or run BTstack on Linux with an USB Bluetooth dongle."

Could you explain ?
I am very sorry.
Best regards.

**Comment by mringwal** [comment]
To use the BCM20733 please contact Cypress sales team, not us.
I recommend you use a different port. The ESP32 is not that bad and you managed to get BTstack to run on it, just not the serial monitor.

**Comment by WallGeorg** [comment]
Hi.
I found BCM20733 in SDK2.2.3.
What is mean?
![screen1](https://user-images.githubusercontent.com/30696128/29574584-48687b24-8762-11e7-98c6-f4fb444f2935.png)
Could you explain?
Please help me?

**Comment by mringwal** [comment]
This ifdef is probably for code that runs on the 20733 itself. Again, help from Infineon/Cypress is needed here.
