### ISSUE TITLE
esp32/spp_streamer example with EDR

### ISSUE THREAD

**Issue by asuivelentine** [bluekitchen/btstack#68]
Hi,
could you please add an EDR configuration to spp_streamer?

The current throughput is ~ `674400 bytes -> 224.500 kB/s`.
From my understanding it should be possible to get data rates of ~ 1-2 mB/s using EDR ->
What do I need  to change to get those throughput?

Thank you.

**Comment by mringwal** [comment]
EDR is fully used. The throughput is reported in kilobytes per seconds. with 224.5 this results in 1796 kilobit (kbps)
