### ISSUE TITLE
iOS xcode compile error

### ISSUE THREAD

**Issue by shattars3d** [bluekitchen/btstack#7]
#include <btstack/utils.h>   #import <btstack/btstack.h>

are missing and won't compile in Xcode 6.4 hmm,... are they in the btstack folder? or...

please let me know thanks...

**Comment by mringwal** [comment]
The BTstack package is compiled with make on the command line. Please have a look at the the just updated [ReadMe](https://github.com/bluekitchen/btstack/tree/master/platforms/ios).
