### ISSUE TITLE
Multiple connections impossible

### ISSUE THREAD

**Issue by jbonsant** [bluekitchen/btstack#70]
I am on esp32 and I find impossible to have more than one connection to my Bluetooth peripheral. 
When I try the other connection I have this error:
`acl_handler called with non-registered handle 1`

**Comment by mringwal** [comment]
Hi. It should work. Could you do a git pull on develop or master branch, run ./create_examples.py, and try le_counter example again?
If it really fails, please copy & paste the console output with the full packet log enabled (by default) into a file and run tool/create_packet_log.py your-log-file.txt and post this one. You can open it Wireshark.
