### ISSUE TITLE
Notifications of large size

### ISSUE THREAD

**Issue by maximzakharov** [bluekitchen/btstack#74]
Is it possible to use btstack for a peripheral device to provide transmission over notifications of packets larger than 20 bytes in size?

**Comment by mringwal** [comment]
Probably. A notification can have up to ATT MTU - 3 bytes of data. The default MTU is 23 bytes, however the GATT Client can negotiate a higher ATT MTU. iOS usually suggests 158 or 185 bytes ATT MTU. 

The le_streamer and le_streamer_client from BTstack will use ATT MTUs of up to 200 bytes.

Please post general questions on the BTstack Developer Mailing List (a google group) as this is not an issue of BTstack.
