### ISSUE TITLE
A2DP Sink demo does not link on f4discovery-cc256x

### ISSUE THREAD

**Issue by arabine** [bluekitchen/btstack#83]
It seems that there is no more space in RAM:

/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: a2dp_sink_demo.elf section `.bss' will not fit in region `RAM'
/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 2440 bytes

Have you any suggestions to lower the RAM usage by, for instance, changing the stack configuration?

Edit: the link script defines a RAM space too low for a STM32F407 processor (20k defined)

**Comment by mringwal** [comment]
hi, thanks for pointing this out. Looks like the mem.ld file is not correct. (and there also was an unimportant compile error).
I've updated the mem.ld to announce 1024 kB Flash and 128 kB RAM on the develop branch. 
Could you give this a try?
