### ISSUE TITLE
iOS build error 

### ISSUE THREAD

**Issue by shattars3d** [bluekitchen/btstack#9]
![screen shot 2015-07-13 at 2 45 00 pm](https://cloud.githubusercontent.com/assets/2119331/8657811/db996534-296d-11e5-93fc-b658be7db42b.png)

having compiling issues/errors.. what is the work around this?...

**Comment by mringwal** [comment]
Can you run the file command in a terminal against libBTstack.dylib?
Did you copy it from your iOS device?

I get:

    $ file libBTstack.dylib
    libBTstack.dylib: Mach-O universal binary with 2 architectures
    libBTstack.dylib (for architecture armv6):	Mach-O dynamically linked shared library arm
    libBTstack.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library

**Comment by shattars3d** [comment]
hey, no… i got my libBTstack.dylib from online.. from some research…  do i have to run any make commands?… because i didn't run..

Go to btstack/platforms/ios and run make

	cd btstack
	make package

If everything went right, you'll end up with a .deb package that you can install via:

	make install

**Comment by mringwal** [comment]
Please try with this version: https://dl.dropboxusercontent.com/u/5138628/libBTstack.dylib

**Comment by shattars3d** [comment]
hey thanks, i have tried your libBTstack.dylib. the Xcode built succeeded but i got this error not when the app is present on the iPad...


![screen shot 2015-07-14 at 10 17 51 am](https://cloud.githubusercontent.com/assets/2119331/8675405/bec421ac-2a11-11e5-9db8-e45d513efb90.png)

**Comment by mringwal** [comment]
Oh. I didn't know that there are still Xcode projects. I gave up on using Xcode for JB development when theos came out and made everything understandable instead of hoping that Xcode wouldn't screw up.

So... I've deleted these projects but updated the Makefile for the WiiMoteOpenGL demo. Please see the updated [README](https://github.com/bluekitchen/btstack/tree/master/platforms/ios)

**Comment by MattSich** [comment]
So there's not way to work with this in xCode? @mringwal

**Comment by mringwal** [comment]
Well, if you like you could setup an Xcode project and compile with it. It's just that you have to maintain the project then. It's also possible to use the existing Makefiles with Xcode as far as I know, it just doesn't work whenever I try - and I'm fine with Makefiles and Sublime Text.
