### ISSUE TITLE
rfc2978_charset_mib_enumid_t enum item conflict

### ISSUE THREAD

**Issue by zaporozhets** [bluekitchen/btstack#90]
Enumeration item UTF8 which is defined in avrcp.h sometimes may conflict with other libraries and causes next compilation errors:
"error: 'typedef unsigned char UTF8' redeclared as different kind of symbol typedef 

Could you, please, suggest how to handle this situation or maybe you could add prefix to UTF8 item (BTSTACK_UTF8, AVRCP_UTF8, etc.)?
Thank you in advance. Cheers.

**Comment by milamikica** [comment]
Hi, thank you for reporting this. We fixed it on master and develop branch by prefixing it, so you'll have now RFC2978_CHARSET_MIB_UTF8 instead of UTF8.

Cheers,
MIla
